import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.navy[50] },
  header: { padding: 20, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: colors.navy[100] },

  title: { fontSize: 22, fontWeight: '900', color: '#0F172A', textTransform: 'uppercase', letterSpacing: -0.5, marginBottom: 15 },
  rightScrollIndicator: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 40,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: 5,
    borderRadius: 10,
  },
  tabsContainer: { flexGrow: 1 },
  tabs: { flex: 1, flexDirection: 'row', backgroundColor: '#f0f0f0', borderRadius: 10, padding: 4, minWidth: '100%' },
  tab: { paddingVertical: 8, paddingHorizontal: 16, alignItems: 'center', borderRadius: 8 },
  activeTab: { backgroundColor: '#fff', elevation: 2 },
  tabText: { fontSize: 13, fontWeight: '700', color: '#64748B' },
  activeTabText: { color: colors.primary.base },
  detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 15, marginTop: 20 },
  detailItem: { width: '45%', flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, backgroundColor: '#F8FAFC', borderRadius: 12 },
  detailLabel: { fontSize: 10, fontWeight: '700', color: '#94A3B8', textTransform: 'uppercase' },
  detailValue: { fontSize: 13, fontWeight: '700', color: '#1E293B' },
  modalActionRow: { flexDirection: 'row', gap: 12, marginTop: 25 },
  venueSearchContainer: { marginTop: 10 },
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, gap: 10 },
  searchInput: { flex: 1, fontSize: 14, color: '#0F172A', padding: 0 },
  venueResults: { maxHeight: 200, marginTop: 12 },
  venueResultItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12, borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: '#F1F5F9', marginBottom: 8 },
  venueResultSelected: { borderColor: '#6366F1', backgroundColor: '#EEF2FF' },
  venueName: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
  venueLoc: { fontSize: 12, color: '#64748B', marginTop: 2 },
  busyLabel: { fontSize: 11, fontWeight: '700', color: '#EF4444', marginTop: 4 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 15,
    marginVertical: 10,
    paddingHorizontal: 15,
    borderRadius: borderRadius.md,
    height: 50,
    ...shadows.sm,
  },
  filtersWrapper: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 5,
  },
  dropdownsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  dropdownBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  dropdownLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  dropdownValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 2,
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  dropdownMenu: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '80%',
  },
  dropdownMenuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  dropdownMenuTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownItemActive: {
    backgroundColor: '#EEF2FF',
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  dropdownItemText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#334155',
  },
  dropdownItemTextActive: {
    fontWeight: '700',
    color: '#3B82F6',
  },
  searchIcon: { marginRight: 10 },
  searchInput: { flex: 1, fontSize: 14, color: colors.navy[900], fontWeight: '500' },
  scoreInput: {
    backgroundColor: '#F1F5F9',
    width: 60,
    height: 50,
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 8
  },
  scoreInput: {
    backgroundColor: '#F1F5F9',
    width: 60,
    height: 50,
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 8
  },
  list: { padding: 15 },
  card: { 
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', 
    padding: 15, borderRadius: borderRadius.lg, marginBottom: 12, ...shadows.sm 
  },
  avatar: { width: 50, height: 50, borderRadius: 25, marginRight: 15 },
  info: { flex: 1 },
  name: { fontSize: 16, fontWeight: '700', color: '#333' },
  details: { fontSize: 12, color: '#666', marginTop: 2 },
  dist: { fontSize: 11, color: colors.primary.base, marginTop: 4, fontWeight: '600' },
  btn: { backgroundColor: colors.primary.base, paddingVertical: 8, paddingHorizontal: 15, borderRadius: 8 },
  btnSent: { backgroundColor: '#ccc' },
  btnText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  tabContent: { flex: 1, padding: 15 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, backgroundColor: '#EF4444' },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '900' },
  responseTag: { backgroundColor: '#F0F9FF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, borderWidth: 1, borderColor: '#BAE6FD' },
  responseTagText: { fontSize: 9, fontWeight: '900', color: '#0369A1' },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#1a1a1a' },
  section: { backgroundColor: 'transparent' },
  requestCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: colors.primary.base, shadowColor: '#94A3B8', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 1 },
  actionRow: { flexDirection: 'row', gap: 10 },
  smallBtn: { backgroundColor: '#f0f0f0', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6 },
  smallBtnText: { fontSize: 12, fontWeight: '700', color: '#333' },
  subTabContainer: { flexDirection: 'row', backgroundColor: '#f0f0f0', borderRadius: 8, padding: 3, marginHorizontal: 15, marginTop: 15, marginBottom: 5 },
  subTab: { flex: 1, paddingVertical: 6, alignItems: 'center', borderRadius: 6 },
  activeSubTab: { backgroundColor: '#fff', elevation: 1 },
  subTabText: { fontSize: 11, fontWeight: '700', color: '#64748B' },
  activeSubTabText: { color: colors.primary.base },
  acceptedCard: { backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 12, elevation: 3 },
  acceptedHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  acceptedTime: { fontSize: 12, color: '#666', fontWeight: '600' },
  acceptedTitle: { fontSize: 16, fontWeight: '700', color: '#334155', marginBottom: 4 },
  acceptedDetail: { fontSize: 13, color: '#64748B' },
  historyCard: { backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 10, elevation: 2 },
  historyName: { fontSize: 15, fontWeight: '700', color: '#333', marginBottom: 4 },
  historyDetail: { fontSize: 13, color: '#666' },
  historySubDetail: { fontSize: 12, color: '#94A3B8', marginTop: 2 },
  historyResult: { fontSize: 14, fontWeight: '800', color: '#16A34A' },
  emptyText: { textAlign: 'center', color: '#94A3B8', marginTop: 0, fontSize: 13, paddingVertical: 10 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '80%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: '900' },
  inputLabel: { fontSize: 14, fontWeight: '700', color: '#333', marginBottom: 8, marginTop: 15 },
  input: { backgroundColor: '#f5f5f5', borderRadius: 10, padding: 12, fontSize: 15 },
  sportGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sportTag: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20, backgroundColor: '#f0f0f0' },
  sportTagActive: { backgroundColor: colors.primary.base },
  sportTagText: { fontSize: 13, fontWeight: '600', color: '#666' },
  sportTagTextActive: { color: '#fff' },
  confirmBtn: { backgroundColor: colors.primary.base, padding: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', marginTop: 30 },
  confirmBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  modalLabel: { fontSize: 10, fontWeight: '900', color: '#6366F1', letterSpacing: 2, marginBottom: 4 },
  modalClose: { padding: 4 },
  sectionLabel: { fontSize: 12, fontWeight: '900', color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12, marginTop: 25 },
  calendarContainer: { borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#F1F5F9' },
  timeSlots: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10, zIndex: 20, overflow: 'visible' },
  slotWrapper: { width: '23%', position: 'relative' },
  slotBtn: { backgroundColor: '#F1F5F9', paddingVertical: 10, paddingHorizontal: 2, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#F1F5F9' },
  slotBtnActive: { backgroundColor: '#EEF2FF', borderColor: '#6366F1' },
  slotText: { fontSize: 11, fontWeight: '900', color: '#64748B', textAlign: 'center' },
  slotTextActive: { color: '#6366F1' },
  subIntervalsPopup: {
    position: 'absolute',
    top: 55,
    left: 0,
    width: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    zIndex: 1000,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  subBtn: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
  },
  subBtnActive: {
    backgroundColor: '#6366F1',
  },
  subBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  subBtnTextActive: {
    color: '#FFF',
  },
  actionBtn: { flex: 1, paddingVertical: 15, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  actionBtnText: { fontSize: 13, fontWeight: '800', color: '#fff' },
  venueRow: { flexDirection: 'column', gap: 10 },
  venueBtn: { flexDirection: 'row', alignItems: 'center', padding: 15, borderRadius: 16, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#F1F5F9', gap: 12 },
  venueBtnActive: { backgroundColor: '#EEF2FF', borderColor: '#6366F1' },
  venueText: { fontSize: 14, fontWeight: '700', color: '#64748B' },
  venueTextActive: { color: '#0F172A' },
  upcomingChallengesSection: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 12,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  emptyUpcomingText: {
    fontSize: 12,
    color: '#94A3B8',
    fontStyle: 'italic',
    textAlign: 'center',
    marginVertical: 8,
  },
  upcomingChallengeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  challengeMeta: {
    width: 80,
  },
  challengeTimeText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  challengeDateText: {
    fontSize: 10,
    color: '#64748B',
  },
  challengeInfoMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 12,
  },
  challengeOpponentText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 2,
  },
  challengeSportText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  // Geoapify Venue Dropdown Styles
  venueSection: {
    marginTop: 10,
    marginBottom: 5,
  },
  venueDropdownContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    maxHeight: 250,
  },
  venueList: {
    padding: 8,
  },
  venueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  venueItemSelected: {
    borderColor: '#6366F1',
    backgroundColor: '#EEF2FF',
  },
  venueName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
  },
  venueNameSelected: {
    color: '#6366F1',
  },
  venueAddress: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    maxWidth: 220,
  },
  venueDistance: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary.base,
  },
  venueContactText: {
    fontSize: 10,
    color: '#64748B',
  },
  venueSportText: {
    fontSize: 11,
    color: '#64748B',
    fontStyle: 'italic',
    marginTop: 1,
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
  },
  loadingText: {
    fontSize: 13,
    color: '#64748B',
    fontStyle: 'italic',
  },
  emptyVenueContainer: {
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#FFF1F2',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FECDD3',
  },
  emptyVenueText: {
    fontSize: 13,
    color: '#E11D48',
    textAlign: 'center',
    marginBottom: 8,
  },
  retryText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E11D48',
    textDecorationLine: 'underline',
  },
  venueDropdownSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 10,
  },
  venueDropdownSearchInput: {
    flex: 1,
    fontSize: 13,
    color: '#0F172A',
    padding: 0,
    fontWeight: '500',
  },
  tabBadge: {
    position: 'absolute',
    top: -8,
    right: -14,
    backgroundColor: '#EF4444',
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    zIndex: 10,
  },
  tabBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '900',
  },
  unreadRequestCard: {
    backgroundColor: '#EFF6FF', // Very light blue background
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6', // Solid blue indicator
  },
  // 🎯 [PHASE 1.2] Suggested Opponents Styles
  suggestedSection: {
    marginBottom: 8,
  },
  suggestedHeader: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 12,
  },
  suggestedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  suggestedTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  suggestedSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: '#94A3B8',
    marginTop: 2,
  },
  suggestionReasonRow: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    marginTop: -4,
  },
  suggestionReasonText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6366F1',
    letterSpacing: 0.2,
  },
  suggestedDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 4,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  dividerText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#94A3B8',
    marginHorizontal: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});

export default styles;
