/**
 * 🔑 Standardized Status Codes
 * Used to decouple service logic from UI messaging.
 */

export const STATUS_CODES = {
  // --- Tournament Operations ---
  PLAYER_REGISTERED: 'PLAYER_REGISTERED',
  TOURNAMENT_FULL: 'TOURNAMENT_FULL',
  JOINED_WAITLIST: 'JOINED_WAITLIST',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  ALREADY_WAITLISTED: 'ALREADY_WAITLISTED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  INTEREST_SUBMITTED: 'INTEREST_SUBMITTED',
  INTEREST_REMOVED: 'INTEREST_REMOVED',
  COACH_OPT_IN_SUCCESS: 'COACH_OPT_IN_SUCCESS',
  
  // --- Payment & Wallet ---
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  
  // --- Auth & Profile ---
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  
  // --- Matches ---
  SCORE_UPDATED: 'SCORE_UPDATED',
  MATCH_COMPLETED: 'MATCH_COMPLETED',
  EVALUATION_SAVED: 'EVALUATION_SAVED',
  
  // --- Matchmaking ---
  CHALLENGE_SENT: 'CHALLENGE_SENT',
  CHALLENGE_ACCEPTED: 'CHALLENGE_ACCEPTED',
  CHALLENGE_DECLINED: 'CHALLENGE_DECLINED',
  CHALLENGE_CANCELLED: 'CHALLENGE_CANCELLED',
  COUNTER_SENT: 'COUNTER_SENT',
  
  // --- Support ---
  TICKET_CREATED: 'TICKET_CREATED',
  ALREADY_SEEN: 'ALREADY_SEEN',
  
  // --- Coach Management ---
  COACH_APPROVED: 'COACH_APPROVED',
  COACH_STATUS_UPDATED: 'COACH_STATUS_UPDATED',
  COACH_ASSIGNED: 'COACH_ASSIGNED',
  COACH_REMOVED: 'COACH_REMOVED',
  
  // --- Tournament Lifecycle ---
  TOURNAMENT_STARTED: 'TOURNAMENT_STARTED',
  TOURNAMENT_CONCLUDED: 'TOURNAMENT_CONCLUDED',
  TOURNAMENT_DELETED: 'TOURNAMENT_DELETED',
  
  // --- System ---
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  OFFLINE: 'OFFLINE'
} as const;

export type StatusCode = keyof typeof STATUS_CODES;
export type ResponseType = 'success' | 'error' | 'warning' | 'info';

export interface ServiceResponse<T = any> {
  success: boolean;
  code: StatusCode;
  type: ResponseType;
  data?: T;
  error?: any;
}
