import express from 'express';
import { AppState, Player, AuditLog } from '../models/index.mjs';
import { asyncHandler } from '../helpers/utils.mjs';
import { apiKeyGuard, authGuard } from '../middleware/security.mjs';
import nodemailer from 'nodemailer';

export default function createInfrastructureRoutes({ 
  syncMutex, 
  logAudit,
  APP_VERSION
}) {
  const router = express.Router();

  // GET /api/infrastructure/status
  router.get('/status', (req, res) => {
    res.json({ success: true, service: 'infrastructure', status: 'healthy', version: APP_VERSION, timestamp: new Date().toISOString() });
  });

  // 🛡️ [SECURITY EXPORT ENDPOINT] (v2.6.376)
  // Requires a signed JWT token generated by a valid Slack interaction
  router.get('/security/export', async (req, res) => {
    try {
      const { token } = req.query;
      if (!token) return res.status(401).send("Unauthorized: Missing forensic token");

      const jwt = await import('jsonwebtoken');
      let decoded;
      try {
        decoded = jwt.default.verify(token, process.env.JWT_SECRET || 'ace_forensics_legacy');
      } catch (e) {
        return res.status(403).send("Forbidden: Forensic token expired or invalid");
      }

      const timeframeHours = decoded.hours || 24;
      const since = new Date(Date.now() - timeframeHours * 60 * 60 * 1000);
      const { SecuritySummary } = await import('../models/index.mjs');
      const summaries = await SecuritySummary.find({ lastEventAt: { $gt: since } }).lean();

      const rawData = { 
        generatedAt: new Date().toISOString(), 
        tokenIssuedAt: new Date(decoded.iat * 1000).toISOString(),
        timeframe: `${timeframeHours}h`, 
        events: summaries 
      };

      const now = new Date();
      const istOffset = 5.5 * 60 * 60 * 1000;
      const istDate = new Date(now.getTime() + istOffset);
      const filename = `security_audit_${String(istDate.getUTCDate()).padStart(2,'0')}${String(istDate.getUTCMonth()+1).padStart(2,'0')}${istDate.getUTCFullYear()}.json`;

      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
      return res.send(JSON.stringify(rawData, null, 2));
    } catch (err) { res.status(500).send("Export failed: " + err.message); }
  });

  // 🛡️ [UNIFIED SLACK GATEWAY] (v2.6.376)
  // Handles both /slack/command and /slack/interact at all potential paths
  router.post('/slack/command', handleSlackUnified);
  router.post('/slack/interact', handleSlackUnified);
  router.post('/infrastructure/slack/command', handleSlackUnified);
  router.post('/infrastructure/slack/interact', handleSlackUnified);

  async function handleSlackUnified(req, res) {
    // 🛡️ [INSTANT ACK] (v2.6.376)
    // Slack requires a 200 OK within 3 seconds. We respond instantly and process in the background.
    res.status(200).send();

    try {
      if (req.body.payload) {
        return await handleInteract(req, res, true); // true = delayed mode
      }

      const { command, text, response_url } = req.body;
      if (command === '/acetrack' && String(text).trim().toLowerCase() === 'security') {
        const { generateSecuritySummaryBlocks } = await import('../services/scheduler.mjs');
        const summary = await generateSecuritySummaryBlocks(24);
        await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", ...summary });
      }
    } catch (err) {
      console.error("❌ Unified Gateway Error:", err.message);
    }
  }

  async function sendDelayedSlackResponse(url, payload) {
    if (!url) return;
    try {
      const https = await import('https');
      const parsedUrl = new URL(url);
      const options = {
        hostname: parsedUrl.hostname,
        path: parsedUrl.pathname + parsedUrl.search,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      };
      const req = https.request(options);
      req.write(JSON.stringify(payload));
      req.end();
    } catch (e) { console.error("Delayed Response Failed:", e.message); }
  }

  async function handleInteract(req, res, isDelayed = false) {
    try {
      const payload = JSON.parse(req.body.payload);
      const responseUrl = payload.response_url;
      
      const actionObj = payload.actions?.[0] || {};
      const actionId = actionObj.action_id || actionObj.name;
      
      await logAudit(req, 'SLACK_INTERACT_RECEIVED', [], {
        user: payload.user?.name,
        actionId: actionId,
        triggerId: payload.trigger_id
      });

      console.log(`📡 [SLACK_ACTION] User: ${payload.user?.name} | Action: ${actionId}`);

      // Handle the Security Summary Drill-down
      if (actionId === 'view_security_details') {
         let timeframe = 24;
         try {
           const actionData = JSON.parse(actionObj.value || '{}');
           timeframe = actionData.timeframe || 24;
         } catch (e) {}

         // 🔐 [SECURITY ENFORCEMENT]: Generate a short-lived forensic token (v2.6.376)
         const jwt = await import('jsonwebtoken');
         const token = jwt.default.sign(
           { hours: timeframe, user: payload.user?.name, type: 'forensic_export' },
           process.env.JWT_SECRET || 'ace_forensics_legacy',
           { expiresIn: '15m' }
         );

         const downloadUrl = `https://acetrack-suggested.onrender.com/security/export?token=${token}`;
         
         const followUpResponse = {
            replace_original: false,
            response_type: "ephemeral",
            blocks: [
              {
                type: "section",
                text: { type: "mrkdwn", text: `📂 *Forensic Report Ready (Last ${timeframe}h)*\nYour secure audit file has been generated and is ready for download.` }
              },
              {
                type: "actions",
                elements: [
                  {
                    type: "button",
                    text: { type: "plain_text", text: "⬇️ Download JSON Report" },
                    style: "primary",
                    url: downloadUrl,
                    action_id: "download_json_report"
                  }
                ]
              },
              {
                type: "context",
                elements: [
                  { type: "mrkdwn", text: "⚠️ _Security Note: This download link expires in 15 minutes._" }
                ]
              }
            ]
         };
         
         if (isDelayed) {
            // First, acknowledge the click to prevent Slack timeout
            await sendDelayedSlackResponse(responseUrl, { 
              replace_original: false, 
              response_type: "ephemeral", 
              text: "🔄 *Generating secure forensic report...* This may take a few seconds." 
            });
            
            // Then, send the actual button after a tiny delay
            return setTimeout(async () => {
              await sendDelayedSlackResponse(responseUrl, followUpResponse);
            }, 2000);
         }
         return res.json(followUpResponse);
      }

      // Handle Approve/Block
      if (actionId === 'security_action' || actionId === 'approve' || actionId === 'block') {
         let actionData = {};
         try { actionData = JSON.parse(actionObj.value || '{}'); } catch (e) {}
         const { action, target, ip } = actionData;
         const finalAction = action || actionId;

         if (finalAction === 'block') {
           const release = await syncMutex.acquire();
           try {
             const appState = await AppState.findOne().sort({ lastUpdated: -1 });
             const players = [...(appState?.data?.players || [])];
             const userIdx = players.findIndex(p => String(p.id).toLowerCase() === String(target).toLowerCase() || String(p.email).toLowerCase() === String(target).toLowerCase());

             if (userIdx !== -1) {
               const now = Date.now();
               players[userIdx].loginBlockedUntil = now + (5 * 60 * 1000);
               players[userIdx].lastForceLogoutAt = now;
               await AppState.findOneAndUpdate({}, { $set: { 'data.players': players, version: appState.version + 1, lastUpdated: now } });
               await Player.updateOne({ id: players[userIdx].id }, { $set: { "data.loginBlockedUntil": players[userIdx].loginBlockedUntil, "data.lastForceLogoutAt": players[userIdx].lastForceLogoutAt, lastUpdated: new Date() } });
               const blockRes = { replace_original: false, text: `🛑 *LOCKDOWN SUCCESSFUL*: Account *${target}* blocked. (Action by: ${payload.user.name})` };
               if (isDelayed) return await sendDelayedSlackResponse(responseUrl, blockRes);
               return res.json(blockRes);
             }
           } finally { release(); }
         } else if (finalAction === 'approve') {
            const appRes = { replace_original: false, text: `✅ *APPROVED*: Login session authorized by ${payload.user.name}.` };
            if (isDelayed) return await sendDelayedSlackResponse(responseUrl, appRes);
            return res.json(appRes);
         }
      }

      // 🛡️ [CATCH-ALL RESPONDER] (v2.6.376)
      const catchRes = {
        replace_original: false,
        response_type: "ephemeral",
        text: `📡 *Handshake Successful* (v${APP_VERSION})\nI received your interaction: \`${actionId}\`. If you don't see the expected result, please run \`/acetrack security\` to get a fresh report.`
      };
      if (isDelayed) return await sendDelayedSlackResponse(responseUrl, catchRes);
      return res.json(catchRes);
    } catch (err) {
      console.error("❌ Slack interaction failed:", err.message);
    }
  }

  return router;
}
