import express from 'express';
import { AppState, Player, AuditLog } from '../models/index.mjs';
import { asyncHandler } from '../helpers/utils.mjs';
import { apiKeyGuard, authGuard } from '../middleware/security.mjs';
import nodemailer from 'nodemailer';

export default function createInfrastructureRoutes({ 
  syncMutex, 
  logAudit,
  APP_VERSION
}) {
  const router = express.Router();

  // GET /api/infrastructure/status
  router.get('/status', (req, res) => {
    res.json({ success: true, service: 'infrastructure', status: 'healthy', version: APP_VERSION, timestamp: new Date().toISOString() });
  });

  // 🛡️ [SECURITY EXPORT ENDPOINT] (v2.6.383)
  // Requires a signed JWT token generated by a valid Slack interaction
  router.get('/security/export', async (req, res) => {
    try {
      const { token } = req.query;
      if (!token) return res.status(401).send("Unauthorized: Missing forensic token");

      const jwt = await import('jsonwebtoken');
      let decoded;
      try {
        decoded = jwt.default.verify(token, process.env.JWT_SECRET || 'ace_forensics_legacy');
      } catch (e) {
        return res.status(403).send("Forbidden: Forensic token expired or invalid");
      }

      const timeframeHours = decoded.hours || 24;
      const since = new Date(Date.now() - timeframeHours * 60 * 60 * 1000);
      const { SecuritySummary } = await import('../models/index.mjs');
      const summaries = await SecuritySummary.find({ lastEventAt: { $gt: since } }).lean();

      const rawData = { 
        generatedAt: new Date().toISOString(), 
        tokenIssuedAt: new Date(decoded.iat * 1000).toISOString(),
        timeframe: `${timeframeHours}h`, 
        events: summaries 
      };

      const now = new Date();
      const istOffset = 5.5 * 60 * 60 * 1000;
      const istDate = new Date(now.getTime() + istOffset);
      const filename = `security_audit_${String(istDate.getUTCDate()).padStart(2,'0')}${String(istDate.getUTCMonth()+1).padStart(2,'0')}${istDate.getUTCFullYear()}.json`;

      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
      return res.send(JSON.stringify(rawData, null, 2));
    } catch (err) { res.status(500).send("Export failed: " + err.message); }
  });

  // 🛡️ [UNIFIED SLACK GATEWAY] (v2.6.383)
  // Handles both /slack/command and /slack/interact at all potential paths
  router.post('/slack/command', handleSlackUnified);
  router.post('/slack/interact', handleSlackUnified);
  router.post('/infrastructure/slack/command', handleSlackUnified);
  router.post('/infrastructure/slack/interact', handleSlackUnified);

  async function handleSlackUnified(req, res) {
    // 🛡️ [VIEW_SUBMISSION FIX] (v2.6.543)
    // Slack view_submission payloads MUST receive the response_action in the HTTP body.
    // We cannot pre-flush a blank 200 for these — let the handler respond directly.
    if (req.body.payload) {
      try {
        const peek = JSON.parse(req.body.payload);
        if (peek.type === 'view_submission') {
          // Route directly WITHOUT pre-flushing. The handler will res.json() the modal dismissal.
          return await handleInteract(req, res, false);
        }
      } catch(e) { /* parse failed, fall through to normal flow */ }
    }

    // 🛡️ [INSTANT ACK] (v2.6.383)
    // For slash commands and block_actions, Slack requires a 200 OK within 3 seconds.
    res.status(200).send();

    try {
      if (req.body.payload) {
        return await handleInteract(req, res, true); // true = delayed mode
      }

      const { command, text, response_url } = req.body;
      if (command === '/acetrack' && String(text).trim().toLowerCase() === 'security') {
        const { generateSecuritySummaryBlocks } = await import('../services/scheduler.mjs');
        const summary = await generateSecuritySummaryBlocks(24);
         await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", replace_original: true, ...summary });
      } else if (command === '/acetrack' && String(text).trim().toLowerCase() === 'queue') {
         const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
         
         const blocks = [
            {
               "type": "header",
               "text": { "type": "plain_text", "text": "🎯 Support Dashboard Initialization", "emoji": true }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "Please select a date range and click *Generate Report* to view the Analytics & Workload:" }
            },
            {
               "type": "actions",
               "block_id": "queue_date_range_block",
               "elements": [
                  {
                     "type": "datepicker",
                     "initial_date": today,
                     "placeholder": { "type": "plain_text", "text": "Start Date", "emoji": true },
                     "action_id": "queue_start_date"
                  },
                  {
                     "type": "datepicker",
                     "initial_date": today,
                     "placeholder": { "type": "plain_text", "text": "End Date", "emoji": true },
                     "action_id": "queue_end_date"
                  },
                  {
                     "type": "button",
                     "text": { "type": "plain_text", "text": "Generate Report 🚀", "emoji": true },
                     "style": "primary",
                     "value": "submit",
                     "action_id": "queue_range_submit"
                  }
               ]
            }
         ];
         
         await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", replace_original: true, blocks });
      } else if (command === '/acetrack' && String(text).trim().toLowerCase().startsWith('ticket ')) {
         const ticketId = String(text).trim().split(' ')[1];
         if (!ticketId) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: "Please provide a valid ticket ID. Usage: `/acetrack ticket 123456`" });
         }
         
         const { SupportTicket, Player } = await import('../models/index.mjs');
         const ticket = await SupportTicket.findOne({ id: String(ticketId) }).lean();
         
         if (!ticket) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: `⚠️ Support Ticket *${ticketId}* not found in the database.` });
         }
         
         const tData = ticket.data || {};
         const userId = tData.userId || 'Unknown';
         const statusRaw = String(tData.status || 'open');
         const status = statusRaw.toLowerCase();
         const createdAt = tData.createdAt || tData.timestamp || ticket.lastUpdated;
         const issueDesc = tData.description || tData.issue || tData.message || 'No description provided';
         const assignedTo = tData.assignedTo;
         
         // Fetch user details
         const user = await Player.findOne({ id: userId }).lean();
         const uData = user?.data || {};
         const userName = uData.firstName ? `${uData.firstName} ${uData.lastName || ''}` : uData.email || userId;
         const userPhone = uData.phoneNumber || uData.phone || 'Not provided';
         
         // Fetch assigned agent details
         let agentName = "Unassigned";
         if (assignedTo) {
             const agent = await Player.findOne({ id: assignedTo }).lean();
             const aData = agent?.data || {};
             agentName = aData.firstName ? `${aData.firstName} ${aData.lastName || ''} (${aData.email})` : (aData.email || assignedTo);
         }
         
         // AI Summary Generation
         let summary = "Generating AI summary...";
         const apiKey = process.env.GROQ_API_KEY;
         
         if (apiKey) {
            try {
               let chatHistory = "No conversation history found.";
               if (tData.messages && Array.isArray(tData.messages)) {
                   chatHistory = tData.messages.map(m => `[${m.senderId || m.sender || 'User'}]: ${m.text || m.content || m.message || ''}`).join('\n');
               } else if (ticket.messages && Array.isArray(ticket.messages)) {
                   chatHistory = ticket.messages.map(m => `[${m.senderId || m.sender || 'User'}]: ${m.text || m.content || m.message || ''}`).join('\n');
               }
               
               const prompt = `You are a Customer Support AI Assistant. Summarize the support ticket below. 
You MUST format your response EXACTLY like this (use standard bullet points, and ensure EVERY bullet point is on a NEW LINE, do not include any extra text or pleasantries):

• [Bullet point 1 summarizing the core issue]
• [Bullet point 2 summarizing the conversation history]
• [Bullet point 3 summarizing the current state]

*Next Step:* [1 clear, highly actionable next step for the support agent]

Ticket Description: ${issueDesc}
Chat History:
${chatHistory.substring(0, 3000)}`;

               const aiReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
                 method: 'POST',
                 headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
                 body: JSON.stringify({
                   model: "llama-3.3-70b-versatile",
                   messages: [{ role: 'user', content: prompt }],
                   temperature: 0.3,
                   max_tokens: 300
                 })
               });
               
               if (aiReq.ok) {
                  const aiJson = await aiReq.json();
                  let rawContent = aiJson.choices?.[0]?.message?.content || "AI returned empty response.";
                  
                  // Force a newline before every bullet point if the AI missed it
                  summary = rawContent.replace(/(?<!\n)(•|-)/g, '\n$1').trim();
               } else {
                  let errorBody = await aiReq.text();
                  try { 
                     const p = JSON.parse(errorBody);
                     if (p.error && p.error.message) errorBody = p.error.message;
                  } catch(e){}
                  summary = `_AI Error (${aiReq.status}): ${aiReq.statusText || 'Request Failed'} - ${errorBody}_`;
               }
            } catch (e) {
               summary = `_AI Generation Failed: ${e.message}_`;
            }
         } else {
            summary = "_AI Summary unavailable: GROQ_API_KEY is not set on the backend._";
         }
         
         const ticketFields = [
            { "type": "mrkdwn", "text": `*Raised By:*\n${userName}` },
            { "type": "mrkdwn", "text": `*Contact Number:*\n${userPhone}` },
            { "type": "mrkdwn", "text": `*Assigned To:*\n${agentName}` },
            { "type": "mrkdwn", "text": `*Status:*\n\`${statusRaw.toUpperCase()}\`` },
            { "type": "mrkdwn", "text": `*Opened On:*\n${new Date(createdAt).toLocaleString()}` }
         ];

         if (status === 'closed' || status === 'resolved') {
            const closedAt = tData.closedAt || tData.resolvedAt || ticket.lastUpdated;
            ticketFields.push({ "type": "mrkdwn", "text": `*Closed On:*\n${new Date(closedAt).toLocaleString()}` });
         }
         
         const blocks = [
            {
               "type": "header",
               "text": { "type": "plain_text", "text": `🎫 Ticket #${ticketId}`, "emoji": true }
            },
            {
               "type": "section",
               "fields": ticketFields
            },
            { "type": "divider" },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": `*Issue Description:*\n> ${issueDesc}` }
            },
            { "type": "divider" },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": `*🤖 AI Conversation Summary & Next Steps:*\n${summary}` }
            }
         ];
         
         await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", blocks });
      } else if (command === '/acetrack' && String(text).trim().toLowerCase() === 'help') {
         const blocks = [
            {
               "type": "header",
               "text": { "type": "plain_text", "text": "🛠️ AceTrack Slash Commands", "emoji": true }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "*`/acetrack security`*\nGenerates a security summary report for the last 24 hours." }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "*`/acetrack queue`*\nOpens the Support Dashboard to view ticket analytics over a date range." }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "*`/acetrack ticket <id>`*\nFetches details and an AI summary of a specific support ticket.\n_Example: `/acetrack ticket 123456`_" }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "*`/acetrack logs <query>`*\nUses AI to search and summarize system logs (MongoDB & Filesystem) based on natural language.\n_Example: `/acetrack logs were there any critical server panics today?`_" }
            },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "*`/acetrack query <json>`*\nExecutes a raw JSON MongoDB query directly against the AuditLog collection.\n_Example: `/acetrack query {\"action\": \"UNAUTHORIZED_ACCESS_BLOCKED\"}`_" }
            }
         ];
         return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", replace_original: true, blocks });
      } else if (command === '/acetrack' && String(text).trim().toLowerCase().startsWith('logs ')) {
         const userQuery = String(text).trim().substring(5).trim();
         if (!userQuery) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: "Please provide a query. Usage: `/acetrack logs was there any recent password change activity`" });
         }

         await runLogAI(userQuery, response_url, false);
      } else if (command === '/acetrack' && String(text).trim().toLowerCase().startsWith('query ')) {
         const userQuery = String(text).trim().substring(6).trim();
         if (!userQuery) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: "Please provide a valid JSON query. Usage: `/acetrack query {\"action\":\"LOGIN\"}`" });
         }

         let queryObj;
         try {
            queryObj = JSON.parse(userQuery);
            if (queryObj && typeof queryObj === 'object' && queryObj.mongoFilter) {
               queryObj = queryObj.mongoFilter;
            }
         } catch (e) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: `⚠️ *Invalid JSON:* ${e.message}` });
         }

         const { AuditLog } = await import('../models/index.mjs');
         let mongoLogs = [];
         try {
            mongoLogs = await AuditLog.find(sanitizeMongoFilter(queryObj)).sort({ timestamp: -1 }).limit(50).lean();
         } catch (e) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: `⚠️ *MongoDB Error:* ${e.message}` });
         }

         if (mongoLogs.length === 0) {
            return await sendDelayedSlackResponse(response_url, { response_type: "ephemeral", text: `🔍 *Query:* \`${userQuery}\`\n\n*Result:* No logs found.` });
         }

         // Pass raw results through AI for a clean summary
         await runQueryAI(userQuery, mongoLogs, response_url);
      }
    } catch (err) {
      console.error("❌ Unified Gateway Error:", err.message);
    }
  }

  async function sendDelayedSlackResponse(url, payload) {
    if (!url) return;
    try {
      const https = await import('https');
      const parsedUrl = new URL(url);
      const options = {
        hostname: parsedUrl.hostname,
        path: parsedUrl.pathname + parsedUrl.search,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' }
      };
      const req = https.request(options, (res) => {
         let data = '';
         res.on('data', chunk => data += chunk);
         res.on('end', () => {
             if (res.statusCode >= 400) {
                 console.error(`Slack Response Error (${res.statusCode}):`, data);
             }
         });
      });
      req.on('error', (e) => console.error("Delayed Response Req Error:", e.message));
      req.write(JSON.stringify(payload));
      req.end();
    } catch (e) { console.error("Delayed Response Failed:", e.message); }
  }

  async function handleInteract(req, res, isDelayed = false) {
    try {
      const payload = JSON.parse(req.body.payload);
      
      if (payload.type === 'view_submission') {
         if (payload.view.callback_id === 'mfa_pin_modal') {
            const stateValues = payload.view.state.values;
            const submittedPin = stateValues.pin_block.pin_input.value;
            
            const ADMIN_MFA_PIN = process.env.ADMIN_MFA_PIN || '120522';
            if (submittedPin !== ADMIN_MFA_PIN) {
               return res.json({
                  response_action: 'errors',
                  errors: {
                     pin_block: 'Invalid Admin MFA PIN.'
                  }
               });
            }

            // ✅ Dismiss the modal immediately via HTTP response body
            res.json({ response_action: 'clear' });

            // 🔓 [MFA REVEAL FIX] (v2.6.544)
            // view_submission payloads do NOT carry a response_url.
            // Use chat.postEphemeral + response_url fallback to deliver unredacted results.
            try {
               const meta = JSON.parse(payload.view.private_metadata);
               const { query, channelId, userId, responseUrl: storedUrl, intent } = meta;
               console.log('📡 [MFA_REVEAL] Parsed metadata:', { query: query?.substring(0, 30), channelId, userId, hasUrl: !!storedUrl });
               
               runLogAIEphemeral(query, channelId, userId, storedUrl, intent).catch(e => console.error('MFA Reveal Error:', e));
            } catch(e) {
               console.error("MFA View parsing error:", e);
            }
            return;
         }
      }

      const responseUrl = payload.response_url;
      const actionObj = payload.actions?.[0] || {};
      const actionId = actionObj.action_id || actionObj.name;
      
      await logAudit(req, 'SLACK_INTERACT_RECEIVED', [], {
        user: payload.user?.name,
        actionId: actionId,
        triggerId: payload.trigger_id
      });

      console.log(`📡 [SLACK_ACTION] User: ${payload.user?.name} | Action: ${actionId}`);

      // Ignore intermediate datepicker changes before submit
      if (actionId === 'queue_start_date' || actionId === 'queue_end_date') {
         return; 
      }

      // 📊 Handle Queue Date Range Submit (v2.6.435)
      if (actionId === 'queue_range_submit') {
         const stateValues = payload.state?.values?.queue_date_range_block || {};
         const startDateStr = stateValues.queue_start_date?.selected_date;
         const endDateStr = stateValues.queue_end_date?.selected_date;
         
         if (!startDateStr || !endDateStr) {
             return await sendDelayedSlackResponse(responseUrl, {
                 replace_original: false,
                 response_type: "ephemeral",
                 text: "⚠️ Please select both a Start Date and an End Date before generating the report."
             });
         }
         
         const startOfDate = new Date(startDateStr);
         startOfDate.setHours(0, 0, 0, 0);
         const endOfDate = new Date(endDateStr);
         endOfDate.setHours(23, 59, 59, 999);
         
         const { SupportTicket, Player } = await import('../models/index.mjs');
         
         const query = {
             $or: [
                 { "data.createdAt": { $gte: startOfDate.toISOString(), $lte: endOfDate.toISOString() } },
                 { "data.closedAt": { $gte: startOfDate.toISOString(), $lte: endOfDate.toISOString() } },
                 { "data.resolvedAt": { $gte: startOfDate.toISOString(), $lte: endOfDate.toISOString() } },
                 // Fallback for cases where dates might be stored as Date objects instead of strings (v2.6.462)
                 { "data.closedAt": { $gte: startOfDate, $lte: endOfDate } },
                 { "data.resolvedAt": { $gte: startOfDate, $lte: endOfDate } }
             ]
         };
         
         // 🛡️ [FILTER_FIX] (v2.6.453): Remove the automatic inclusion of all open tickets 
         // when today is selected. This ensures the report strictly respects the chosen range.
         const tickets = await SupportTicket.find(query).lean();
         
         let totalOpen = 0, totalClosed = 0, totalUnassigned = 0;
         const employeeStats = {};
         
         tickets.forEach(doc => {
            const t = doc.data || {};
            const status = String(t.status || 'open').toLowerCase();
            const isOpen = status !== 'resolved' && status !== 'closed';
            
            if (isOpen) totalOpen++;
            else totalClosed++;
            
            if (!t.assignedTo) {
               if (isOpen) totalUnassigned++;
            }
            
            // Track ALL tickets in employee breakdown (including unassigned/closed)
            const agent = t.assignedTo ? t.assignedTo : 'system_unassigned';
            if (!employeeStats[agent]) employeeStats[agent] = { assigned: 0, open: 0, closed: 0 };
            employeeStats[agent].assigned++;
            if (isOpen) employeeStats[agent].open++;
            else employeeStats[agent].closed++;
         });

         // 👤 Resolve Agent IDs to Names
         const agentIds = Object.keys(employeeStats).filter(id => id !== 'system_unassigned');
         const agentProfiles = await Player.find({ id: { $in: agentIds } }).lean();
         const agentMap = {
             'system_unassigned': '🤖 System / Auto-Resolved (Unassigned)'
         };
         
         agentProfiles.forEach(p => {
             const pd = p.data || {};
             const name = pd.firstName && pd.lastName ? `${pd.firstName} ${pd.lastName}` : '';
             agentMap[p.id] = name ? `${name} (${pd.email || p.id})` : (pd.email || p.id);
         });

         const blocks = [
            {
               "type": "header",
               "text": { "type": "plain_text", "text": "🎯 Support Queue Analytics", "emoji": true }
            },
            {
               "type": "context",
               "elements": [
                  { "type": "mrkdwn", "text": `🗓️ *Report Range:* ${startDateStr} to ${endDateStr}  |  🤖 *Generated By:* AceTrack System` }
               ]
            },
            { "type": "divider" },
            {
               "type": "section",
               "fields": [
                  { "type": "mrkdwn", "text": `*🔥 Active / Open:*\n\`${totalOpen}\` tickets` },
                  { "type": "mrkdwn", "text": `*⏳ Unassigned:*\n\`${totalUnassigned}\` tickets` },
                  { "type": "mrkdwn", "text": `*✅ Closed / Resolved:*\n\`${totalClosed}\` tickets` },
                  { "type": "mrkdwn", "text": `*📈 Total Volume:*\n\`${totalOpen + totalClosed}\` tickets` }
               ]
            },
            { "type": "divider" },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": "👤 *Agent Performance Breakdown*" }
            }
         ];
         
         if (agentIds.length > 0) {
            let agentText = "";
            for (const [agentId, stats] of Object.entries(employeeStats)) {
               const resolvedName = agentMap[agentId] || agentId;
               agentText += `• *${resolvedName}*\n> \`${stats.open}\` Open  |  \`${stats.closed}\` Closed  |  *${stats.assigned}* Total\n\n`;
            }
            blocks.push({
               "type": "section",
               "text": { "type": "mrkdwn", "text": agentText }
            });
         } else {
            blocks.push({
               "type": "section",
               "text": { "type": "mrkdwn", "text": "_No agent activity recorded for this specific date range._" }
            });
         }
         
         const reply = { replace_original: true, response_type: "ephemeral", blocks };
         if (isDelayed) return await sendDelayedSlackResponse(responseUrl, reply);
         return res.json(reply);
      }

      // Handle the Security Summary Drill-down
      if (actionId === 'view_security_details') {
         let timeframe = 24;
         try {
           const actionData = JSON.parse(actionObj.value || '{}');
           timeframe = actionData.timeframe || 24;
         } catch (e) {}

         // 🔐 [SECURITY ENFORCEMENT]: Generate a short-lived forensic token (v2.6.383)
         const jwt = await import('jsonwebtoken');
         const token = jwt.default.sign(
           { hours: timeframe, user: payload.user?.name, type: 'forensic_export' },
           process.env.JWT_SECRET || 'ace_forensics_legacy',
           { expiresIn: '15m' }
         );

         const downloadUrl = `https://acetrack-suggested.onrender.com/security/export?token=${token}`;
         
         const followUpResponse = {
            replace_original: false,
            response_type: "ephemeral",
            blocks: [
              {
                type: "section",
                text: { type: "mrkdwn", text: `📂 *Forensic Report Ready (Last ${timeframe}h)*\nYour secure audit file has been generated and is ready for download.` }
              },
              {
                type: "actions",
                elements: [
                  {
                    type: "button",
                    text: { type: "plain_text", text: "⬇️ Download JSON Report" },
                    style: "primary",
                    url: downloadUrl,
                    action_id: "download_json_report"
                  }
                ]
              },
              {
                type: "context",
                elements: [
                  { type: "mrkdwn", text: "⚠️ _Security Note: This download link expires in 15 minutes._" }
                ]
              }
            ]
         };
         
         if (isDelayed) {
            // First, acknowledge the click to prevent Slack timeout
            await sendDelayedSlackResponse(responseUrl, { 
              replace_original: false, 
              response_type: "ephemeral", 
              text: "🔄 *Generating secure forensic report...* This may take a few seconds." 
            });
            
            // Then, send the actual button after a tiny delay
            return setTimeout(async () => {
              await sendDelayedSlackResponse(responseUrl, followUpResponse);
            }, 2000);
         }
         return res.json(followUpResponse);
      }

      // Handle Approve/Block
      if (actionId === 'security_action' || actionId === 'approve' || actionId === 'block') {
         let actionData = {};
         try { actionData = JSON.parse(actionObj.value || '{}'); } catch (e) {}
         const { action, target, ip } = actionData;
         const finalAction = action || actionId;

         if (finalAction === 'block') {
           const release = await syncMutex.acquire();
           try {
             const appState = await AppState.findOne().sort({ lastUpdated: -1 });
             const players = [...(appState?.data?.players || [])];
             const userIdx = players.findIndex(p => String(p.id).toLowerCase() === String(target).toLowerCase() || String(p.email).toLowerCase() === String(target).toLowerCase());

             if (userIdx !== -1) {
               const now = Date.now();
               players[userIdx].loginBlockedUntil = now + (5 * 60 * 1000);
               players[userIdx].lastForceLogoutAt = now;
               await AppState.findOneAndUpdate({}, { $set: { 'data.players': players, version: appState.version + 1, lastUpdated: now } });
               await Player.updateOne({ id: players[userIdx].id }, { $set: { "data.loginBlockedUntil": players[userIdx].loginBlockedUntil, "data.lastForceLogoutAt": players[userIdx].lastForceLogoutAt, lastUpdated: new Date() } });
               const blockRes = { replace_original: false, text: `🛑 *LOCKDOWN SUCCESSFUL*: Account *${target}* blocked. (Action by: ${payload.user.name})` };
               if (isDelayed) return await sendDelayedSlackResponse(responseUrl, blockRes);
               return res.json(blockRes);
             }
           } finally { release(); }
         } else if (finalAction === 'approve') {
            const appRes = { replace_original: false, text: `✅ *APPROVED*: Login session authorized by ${payload.user.name}.` };
            if (isDelayed) return await sendDelayedSlackResponse(responseUrl, appRes);
            return res.json(appRes);
         }
      }

      // 🛡️ [CATCH-ALL RESPONDER] (v2.6.383)
      const catchRes = {
        replace_original: false,
        response_type: "ephemeral",
        text: `📡 *Handshake Successful* (v${APP_VERSION})\nI received your interaction: \`${actionId}\`. If you don't see the expected result, please run \`/acetrack security\` to get a fresh report.`
      };

      if (actionId === 'reveal_secure_details') {
         let query = '';
         let sourceUrl = '';
         let intent = null;
         try {
            const parsed = JSON.parse(actionObj.value || '{}');
            query = parsed.query;
            sourceUrl = parsed.url;
            intent = parsed.intent;
         } catch(e) {}

         // 🔓 [MFA REVEAL FIX] (v2.6.544)
         // Store channelId + userId + responseUrl in metadata for dual delivery
         const channelId = payload.channel?.id || payload.container?.channel_id;
         const userId = payload.user?.id;
         const targetUrl = responseUrl || sourceUrl; // Prioritize button click responseUrl to perfectly replace the specific message
         console.log('📡 [REVEAL_BTN] Captured context:', { channelId, userId, hasTargetUrl: !!targetUrl });
         const freshMeta = JSON.stringify({ query, channelId, userId, responseUrl: targetUrl, intent });
         const slackBotToken = process.env.SLACK_BOT_TOKEN;
         
         if (!slackBotToken) {
            return await sendDelayedSlackResponse(responseUrl, {
               response_type: "ephemeral",
               text: "⚠️ *Configuration Error:* SLACK_BOT_TOKEN is not set on the server. Cannot open MFA modal."
            });
         }

         if (!isDelayed) res.status(200).send();

         try {
            const openRes = await fetch('https://slack.com/api/views.open', {
               method: 'POST',
               headers: {
                  'Authorization': `Bearer ${slackBotToken}`,
                  'Content-Type': 'application/json'
               },
               body: JSON.stringify({
                  trigger_id: payload.trigger_id,
                  view: {
                     type: "modal",
                     callback_id: "mfa_pin_modal",
                     private_metadata: freshMeta,
                     title: { type: "plain_text", text: "Security Verification" },
                     submit: { type: "plain_text", text: "Verify" },
                     close: { type: "plain_text", text: "Cancel" },
                     blocks: [
                        {
                           type: "input",
                           block_id: "pin_block",
                           element: {
                              type: "plain_text_input",
                              action_id: "pin_input",
                              placeholder: { type: "plain_text", text: "Enter Admin PIN" }
                           },
                           label: { type: "plain_text", text: "Admin MFA PIN" }
                        }
                     ]
                  }
               })
            });
            const openJson = await openRes.json();
            if (!openJson.ok) console.error('Slack views.open failed:', openJson.error);
         } catch(e) {
            console.error("Slack views.open error:", e);
         }
         return;
      }
      
      if (!isDelayed) res.status(200).send();
    } catch (err) {
      console.error("❌ Slack interaction failed:", err.message);
    }
  }

   // 🛡️ [FILTER SANITIZER] (v2.6.545)
   // Fixes common AI-generated MongoDB filter mistakes before execution
   function sanitizeMongoFilter(filter) {
      if (!filter || typeof filter !== 'object') return {};
      const f = JSON.parse(JSON.stringify(filter)); // deep clone

      // Fix 1: Broaden action regex to include UNAUTHORIZED for login queries
      if (f.action && f.action.$regex) {
         const r = f.action.$regex;
         if (/login/i.test(r) && !/unauthorized/i.test(r)) {
            f.action.$regex = `${r}|UNAUTHORIZED`;
         }
      }

      // Fix 2: Convert string timestamps to Date objects
      if (f.timestamp) {
         if (f.timestamp.$gte && typeof f.timestamp.$gte === 'string') f.timestamp.$gte = new Date(f.timestamp.$gte);
         if (f.timestamp.$lte && typeof f.timestamp.$lte === 'string') f.timestamp.$lte = new Date(f.timestamp.$lte);
      }

      // Fix 3: $regex on 'details' (an object field) is invalid — convert to $or on sub-fields
      if (f.details && (f.details.$regex || f.details.$options)) {
         const searchTerm = f.details.$regex || '';
         const opts = f.details.$options || 'i';
         delete f.details;
         const detailsOr = [
            { 'details.email': { $regex: searchTerm, $options: opts } },
            { 'details.name': { $regex: searchTerm, $options: opts } },
            { 'details.identifier': { $regex: searchTerm, $options: opts } },
            { 'details.role': { $regex: searchTerm, $options: opts } },
            { 'details.userId': { $regex: searchTerm, $options: opts } },
            { 'details.receivedIdentifier': { $regex: searchTerm, $options: opts } },
         ];
         if (f.$or) {
            f.$or.push(...detailsOr);
         } else {
            f.$or = detailsOr;
         }
      }

      return f;
   }

   // 🔎 [QUERY AI SUMMARIZER] (v2.6.545)
   // Summarizes raw MongoDB results via AI for /acetrack query
   async function runQueryAI(originalQuery, mongoLogs, responseUrl) {
      const apiKey = process.env.GROQ_API_KEY;

      const compactLogsArr = mongoLogs.map(l => {
         let d = ''; try { d = JSON.stringify(l.details || {}); } catch(e){}
         const istDate = new Date(l.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
         const ip = l.ipAddress ? ` IP:${l.ipAddress}` : '';
         return `[${istDate}] User:${l.userId}${ip} Action:${l.action} Details:${d}`;
      });

      const ipGeoMap = await resolveIpGeoLocations(compactLogsArr);
      const geoMapStr = Object.keys(ipGeoMap).length > 0 
         ? `\n\nIP Geolocation Map (use this to show location next to every IP):\n${Object.entries(ipGeoMap).map(([ip, loc]) => `  ${ip} → ${loc}`).join('\n')}`
         : '';

      const compactLogs = compactLogsArr.join('\n');
      let summaryContent = compactLogs.substring(0, 2500);

      if (apiKey) {
         try {
            const summaryPrompt = `You are a system administrator AI. A user ran a direct MongoDB query: \`${originalQuery}\`

Here are the raw results (${mongoLogs.length} documents):
${compactLogs.substring(0, 12000)}${geoMapStr}

Provide a highly structured, visually clean summary of these results.

⚠️⚠️ ABSOLUTELY CRITICAL RULES:
- You MUST sort ALL events strictly by timestamp in DESCENDING order (most recent event FIRST). Do NOT group by status.
- You MUST output all timestamps in IST (Indian Standard Time).
- You MUST number events sequentially (1, 2, 3...) where #1 is the MOST RECENT event.
- For EVERY IP address you display, you MUST append the geographic location in parentheses using the IP Geolocation Map provided above. Format: \`IP_ADDRESS\`(City). If an IP has no geo data, show \`IP_ADDRESS\`(Unknown).
- Use emojis for visual separation (🚨 failures, ✅ successes, 📍 location, 🔑 passwords).
- Organize the data into clear, distinct sections (e.g., 'Query Results').
- NEVER display internal system IDs starting with 'sup_'. Use 'details.identifier' or 'details.email' instead.
🛡️ SECURITY EXCEPTION: Reveal all IPs, emails, and details without masking.`;

            const aiReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
               method: 'POST',
               headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
               body: JSON.stringify({
                  model: "llama-3.3-70b-versatile",
                  messages: [{ role: 'user', content: summaryPrompt }],
                  temperature: 0.3,
                  max_tokens: 800
               })
            });
            if (aiReq.ok) {
               const aiJson = await aiReq.json();
               summaryContent = aiJson.choices?.[0]?.message?.content || summaryContent;
            }
         } catch(e) {
            console.error('Query AI summary error:', e.message);
         }
      }

      const expTs = Math.floor(Date.now() / 1000) + (30 * 60);
      const blocks = [
         { "type": "header", "text": { "type": "plain_text", "text": "📊 MongoDB Query Result", "emoji": true } },
         { "type": "context", "elements": [
            { "type": "mrkdwn", "text": `*Query:* \`${originalQuery}\`` },
            { "type": "mrkdwn", "text": `*Results:* ${mongoLogs.length} documents` },
            { "type": "mrkdwn", "text": `*<!date^${expTs}^⏳ Auto-expiring at {time}|⏳ Auto-expiring in 30 mins>*` }
         ]},
         { "type": "divider" },
         { "type": "section", "text": { "type": "mrkdwn", "text": summaryContent } }
      ];

      await sendDelayedSlackResponse(responseUrl, { response_type: "ephemeral", replace_original: true, blocks });

      setTimeout(() => {
         sendDelayedSlackResponse(responseUrl, { 
            response_type: "ephemeral", 
            replace_original: true, 
            text: "⏳ *Query Results Expired* - Please run `/acetrack query` again to fetch fresh logs." 
         }).catch(e => console.error("Auto-expire failed:", e));
      }, 29 * 60 * 1000); // 29 mins (Slack response URLs expire after 30 mins)
   }

  async function runLogAI(userQuery, responseUrl, bypassRedaction = false) {
      const apiKey = process.env.GROQ_API_KEY;
      if (!apiKey) {
         return await sendDelayedSlackResponse(responseUrl, { response_type: "ephemeral", text: "⚠️ _AI Query unavailable: GROQ_API_KEY is not set._" });
      }

      try {
         const filterPrompt = `You are an AI Log Router. A user is asking to search logs.
Current Server Time (ISO): ${new Date().toISOString()}

We have two log sources:
1. 'AuditLog' (MongoDB): Contains user actions, authentication events, and security logs.
   Schema: { userId: String, ipAddress: String, userAgent: String, action: String, details: Mixed, timestamp: Date }
   - Common actions: 'SUPPORT_LOGIN_SUCCESS', 'SUPPORT_LOGIN_FAILED', 'ADMIN_LOGIN_SUCCESS', 'ADMIN_LOGIN_FAILED', 'PASSWORD_CHANGED', 'BRUTE_FORCE_DETECTED', 'UNAUTHORIZED_ACCESS_BLOCKED', etc.
   - ⚠️ IMPORTANT: If the user asks about "logins" or "login attempts", you MUST either omit the action filter entirely, or ensure your regex includes "UNAUTHORIZED" alongside "LOGIN" (e.g., {"action": {"$regex": "LOGIN|UNAUTHORIZED", "$options": "i"}}).
   - ⚠️ IMPORTANT: For queries involving usernames or emails (like 'shush' or 'john'), do NOT just query 'userId'. Many events store the target user in 'details.email', 'details.name', 'details.userId', 'details.identifier', 'details.receivedIdentifier'. Use an $or array containing all of these! 
   - ⚠️ IMPORTANT: For IP address queries, search both the 'ipAddress' and 'userId' fields, as 'userId' often stores the IP for unauthenticated attempts.
   - Use $regex heavily for strings! Example for action: { "action": { "$regex": "ADMIN.*LOGIN.*FAIL", "$options": "i" } }
   - ⚠️ CRITICAL: DO NOT use aggregation operators like $date, $subtract, or $$NOW.
   - ⚠️ CRITICAL: ONLY apply a "timestamp" date filter if the user explicitly asks for a specific timeframe (e.g., "today", "yesterday", "last week"). Use the Current Server Time provided above to calculate accurate ISO date strings for $gte/$lte.
2. 'server_events.jsonl' (Filesystem): Contains system crashes, server panics, WebSocket errors, and legacy ephemeral events.

User query: "${userQuery}"

Based on this query, generate a JSON object with two fields:
1. "mongoFilter": A valid MongoDB query object for the AuditLog collection (use $regex heavily for strings!). If the query is broad, return {} to fetch the latest logs.
2. "checkServerEventsFile": A boolean (MUST be true if the query asks about server crashes, panics, WebSocket drops, or system errors).

DO NOT wrap the JSON in markdown code blocks. Output ONLY valid, parsable JSON. No explanations.`;

         const filterReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({
               model: "llama-3.3-70b-versatile",
               messages: [{ role: 'user', content: filterPrompt }],
               temperature: 0.1,
               max_tokens: 300
            })
         });

         let routingIntent = { mongoFilter: {}, checkServerEventsFile: false };
         if (filterReq.ok) {
            const filterJson = await filterReq.json();
            let rawJson = filterJson.choices?.[0]?.message?.content || "{}";
            rawJson = rawJson.replace(/```json/g, '').replace(/```/g, '').trim();
            try {
               routingIntent = JSON.parse(rawJson);
            } catch (e) {
               console.error("AI Routing Parse Error:", e.message, rawJson);
            }
         }

         let combinedLogsArr = [];

         if (Object.keys(routingIntent.mongoFilter || {}).length > 0 || !routingIntent.checkServerEventsFile) {
            const { AuditLog } = await import('../models/index.mjs');
            const sanitizedFilter = sanitizeMongoFilter(routingIntent.mongoFilter);
            let mongoLogs = [];
            try {
               mongoLogs = await AuditLog.find(sanitizedFilter).sort({ timestamp: -1 }).limit(300).lean();
            } catch (err) {
               console.error("MongoDB Query Error (fallback to latest):", err.message);
               mongoLogs = await AuditLog.find({}).sort({ timestamp: -1 }).limit(300).lean();
            }

            // 🔄 [ZERO-RESULT FALLBACK] (v2.6.545)
            // If the sanitized filter returned 0 results, retry without action & timestamp constraints
            if (mongoLogs.length === 0 && Object.keys(sanitizedFilter).length > 0) {
               console.log('[LOG_AI] Zero results with filter, retrying with relaxed constraints');
               const relaxedFilter = { ...sanitizedFilter };
               delete relaxedFilter.action;
               delete relaxedFilter.timestamp;
               try {
                  mongoLogs = await AuditLog.find(Object.keys(relaxedFilter).length > 0 ? relaxedFilter : {}).sort({ timestamp: -1 }).limit(300).lean();
               } catch (err2) {
                  mongoLogs = await AuditLog.find({}).sort({ timestamp: -1 }).limit(300).lean();
               }
            }
            
            const compactMongo = mongoLogs.map(l => {
               let d = ''; try { d = JSON.stringify(l.details || {}); } catch(e){}
               const istDate = new Date(l.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
               const ip = l.ipAddress ? ` IP:${l.ipAddress}` : '';
               return {
                  timeMs: new Date(l.timestamp).getTime() || 0,
                  text: `[Mongo][${istDate}] User:${l.userId}${ip} Action:${l.action} Details:${d}`
               };
            });
            combinedLogsArr.push(...compactMongo);
         }

         if (routingIntent.checkServerEventsFile) {
            const fs = await import('fs');
            const path = await import('path');
            const { fileURLToPath } = await import('url');
            
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);
            const logFile = path.join(__dirname, '..', 'diagnostics', 'server_events.jsonl');
            
            if (fs.existsSync(logFile)) {
               const fileContent = fs.readFileSync(logFile, 'utf8');
               const lines = fileContent.split('\n').filter(Boolean).slice(-300);
               const compactFs = lines.map(line => {
                  let timeMs = 0;
                  try {
                     const obj = JSON.parse(line);
                     if (obj.timestamp) timeMs = new Date(obj.timestamp).getTime();
                  } catch(e) {}
                  return {
                     timeMs,
                     text: `[FS] ${line.substring(0, 500)}`
                  };
               });
               combinedLogsArr.push(...compactFs);
            } else {
               combinedLogsArr.push({ timeMs: 0, text: `[FS] No server_events.jsonl found at ${logFile}` });
            }
         }

         let userSearchTerm = null;
         try {
            const qStr = JSON.stringify(routingIntent.mongoFilter || {});
            const match = qStr.match(/{"\$regex":"([^"|]+)"/);
            if (match && match[1]) {
               userSearchTerm = match[1];
            }
         } catch(e) {}

         if (userSearchTerm && userSearchTerm.length > 2) {
            try {
               const { Player } = await import('../models/index.mjs');
               const playerDoc = await Player.findOne({ 
                  $or: [
                     { id: { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.email': { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.name': { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.username': { $regex: userSearchTerm, $options: 'i' } }
                  ]
               }).lean();

               if (playerDoc) {
                  const pd = playerDoc.data || {};
                  const creationDate = pd.createdAt || pd.reOnboardedAt || playerDoc.lastUpdated;
                  const istDate = new Date(creationDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
                  const istLastUpdated = new Date(playerDoc.lastUpdated).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
                  const profileName = pd.firstName ? `${pd.firstName} ${pd.lastName || ''}`.trim() : (pd.name || 'N/A');
                  const profileEmail = pd.email || 'N/A';
                  const profilePhone = pd.phoneNumber || pd.phone || 'N/A';
                  const profileUsername = pd.username || playerDoc.id || 'N/A';
                  const profileRole = pd.role || 'user';
                  combinedLogsArr.push({
                     timeMs: new Date(creationDate).getTime() || 0,
                     text: `[Database][Fallback Record] System found an active database profile matching "${userSearchTerm}". Name: ${profileName}. Username: ${profileUsername}. Email: ${profileEmail}. Phone: ${profilePhone}. Role: ${profileRole}. Original Onboard/Creation Time: ${istDate}. Last Data Update Time: ${istLastUpdated}.`
                  });
               }
            } catch(e) {
               console.error('Player context fallback failed:', e.message);
            }
         }
         
         if (combinedLogsArr.length === 0) {
            return await sendDelayedSlackResponse(responseUrl, { 
               response_type: "ephemeral", 
               text: `🔍 *Query:* "${userQuery}"\n\n*Result:* No logs found across any system based on AI intent: \`${JSON.stringify(routingIntent)}\`` 
            });
         }

         // 🌍 [GEO-RESOLVE IPs] (v2.6.544)
         const ipGeoMap = await resolveIpGeoLocations(combinedLogsArr);
         const geoMapStr = Object.keys(ipGeoMap).length > 0 
            ? `\n\nIP Geolocation Map (use this to show location next to every IP):\n${Object.entries(ipGeoMap).map(([ip, loc]) => `  ${ip} → ${loc}`).join('\n')}`
            : '';

         // Sort all collected logs strictly by timeMs descending, then map to text strings
         combinedLogsArr.sort((a, b) => b.timeMs - a.timeMs);
         const compactLogs = combinedLogsArr.map(item => item.text).join('\n');

         let securityInstruction = bypassRedaction 
            ? `🛡️ SECURITY EXCEPTION: The administrator has authenticated with MFA. You MUST explicitly reveal all passwords, IP addresses, emails, and sensitive PII that answer the user's query. Do NOT mask them.`
            : `🛡️ ZERO-TRUST GUARDRAIL: ALWAYS mask email addresses, IP addresses, and passwords (e.g., h****@gmail.com, 10.x.x.x, [REDACTED]). Do NOT reveal sensitive PII under any circumstances in this initial summary.`;

         const summaryPrompt = `You are a system administrator AI assistant.
A user asked: "${userQuery}"

${compactLogs.substring(0, 15000)}${geoMapStr}

Please analyze these logs and provide a highly structured, visually clean summary answering the user's question. 

⚠️⚠️ ABSOLUTELY CRITICAL RULES (MUST FOLLOW OR OUTPUT IS INVALID):
- You MUST sort ALL events strictly by timestamp in DESCENDING order (most recent event FIRST, oldest LAST). Do NOT group by status (success/failure) — sort ONLY by time.
- You MUST output all timestamps in IST (Indian Standard Time). If a log is in UTC, convert it to IST.
- You MUST number events sequentially (1, 2, 3...) where #1 is the MOST RECENT event.
- For EVERY IP address you display, you MUST append the geographic location in parentheses using the IP Geolocation Map provided above. Format: \`IP_ADDRESS\`(City). If an IP has no geo data, show \`IP_ADDRESS\`(Unknown).

Formatting rules:
1. Use emojis for visual separation (e.g. 🚨 for failed logins, ✅ for successes, 📍 for location, 🔑 for passwords).
2. Format IPs in inline code blocks followed by location in parentheses: \`1.2.3.4\`(Mumbai).
3. If an IP is a comma-separated list (e.g. "x.x.x.x, proxy1, proxy2"), ONLY extract and display the first IP (the actual client).
4. Organize the data into clear, distinct sections (e.g. 'Incident Report', 'Key Anomalies').
5. For any login or authentication attempts, explicitly state whether the attempt was a SUCCESS or FAILURE based on the log action (e.g., 'LOGIN_SUCCESS' vs 'LOGIN_FAILED').
6. Only include REAL events from the logs. Do NOT fabricate entries like "No other recent login failures found" — if there are fewer events than requested, just show what exists.
7. NEVER display internal system IDs (e.g., ones starting with 'sup_'). Instead, use the 'details.identifier', 'details.email', or 'details.name' from the log. NEVER print 'sup_do8ux1cc' or similar.
8. ALWAYS include the full date (e.g., '22 May 2026') alongside the time for every event.
9. If a '[Database][Fallback Record]' is present, you MUST create an 'Account Information' section AT THE VERY TOP of your summary containing all extracted details (Name, Username, Phone, Email, Role, etc.).
${securityInstruction}`;

         const summaryReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({
               model: "llama-3.3-70b-versatile",
               messages: [{ role: 'user', content: summaryPrompt }],
               temperature: 0.3,
               max_tokens: 800
            })
         });

         let summaryContent = "_AI Summary failed to generate._";
         if (summaryReq.ok) {
            const summaryJson = await summaryReq.json();
            summaryContent = summaryJson.choices?.[0]?.message?.content || summaryContent;
         } else {
            let errorBody = await summaryReq.text();
            try { 
               const p = JSON.parse(errorBody);
               if (p.error && p.error.message) errorBody = p.error.message;
            } catch(e){}
            summaryContent = `_AI Error (${summaryReq.status}): ${summaryReq.statusText || 'Request Failed'} - ${errorBody}_`;
         }

         const blocks = [
            {
               "type": "header",
               "text": { "type": "plain_text", "text": bypassRedaction ? "🔓 Unredacted AI Log Analysis" : "📊 AI Log Analysis", "emoji": true }
            },
            {
               "type": "context",
               "elements": [
                  { "type": "mrkdwn", "text": `*Query:* "${userQuery}"` },
                  { "type": "mrkdwn", "text": `*AI Routing Intent:* \`${JSON.stringify(routingIntent)}\`` },
                  { "type": "mrkdwn", "text": `*Logs Analyzed:* ${combinedLogsArr.length}` }
               ]
            },
            { "type": "divider" },
            {
               "type": "section",
               "text": { "type": "mrkdwn", "text": summaryContent }
            }
         ];

         if (!bypassRedaction) {
             blocks.push({
                "type": "actions",
                "elements": [{
                   "type": "button",
                   "text": { "type": "plain_text", "text": "🔓 Reveal Secure Details" },
                   "style": "danger",
                   "action_id": "reveal_secure_details",
                   "value": JSON.stringify({ query: userQuery, url: responseUrl, intent: routingIntent })
                }]
             });
         }

         const payloadToSend = { 
            response_type: "ephemeral", 
            replace_original: !bypassRedaction, // Slack drops view_submission ephemeral replacements. Force a NEW message if bypassed.
            text: bypassRedaction ? "🔓 Unredacted AI Log Analysis" : "📊 AI Log Analysis",
            blocks 
         };

         await sendDelayedSlackResponse(responseUrl, payloadToSend);

         // 🕒 Auto-Revert after 10 minutes for security
         if (bypassRedaction) {
            setTimeout(() => {
               // Re-run the log AI with bypassRedaction = false to replace the unredacted message with the redacted one
               runLogAI(userQuery, responseUrl, false).catch(e => console.error("Auto-revert failed:", e));
            }, 10 * 60 * 1000); // 10 minutes
         }

      } catch (e) {
         await sendDelayedSlackResponse(responseUrl, { response_type: "ephemeral", text: `⚠️ *Error running log query:* ${e.message}` });
      }
  }

  // 🔓 [MFA REVEAL DELIVERY] (v2.6.544)
  // Runs the same AI log query but delivers results via chat.postEphemeral (Slack Web API)
  // with response_url as fallback, because view_submission payloads don't carry a response_url.
  async function runLogAIEphemeral(userQuery, channelId, slackUserId, fallbackResponseUrl, precalculatedIntent = null) {
      const slackBotToken = process.env.SLACK_BOT_TOKEN;
      
      // We need at least ONE delivery mechanism
      const canEphemeral = slackBotToken && channelId && slackUserId;
      const canResponseUrl = !!fallbackResponseUrl;
      
      if (!canEphemeral && !canResponseUrl) {
         console.error('runLogAIEphemeral: No delivery mechanism available', { channelId, slackUserId, hasToken: !!slackBotToken, hasUrl: canResponseUrl });
         return;
      }
      
      console.log('📡 [MFA_REVEAL_DELIVERY] Delivery paths:', { canEphemeral, canResponseUrl });

      const apiKey = process.env.GROQ_API_KEY;
      if (!apiKey) {
         return await postEphemeral(slackBotToken, channelId, slackUserId, "⚠️ _AI Query unavailable: GROQ_API_KEY is not set._");
      }

      try {
         let routingIntent = precalculatedIntent;
         if (!routingIntent) {
            // 1. Route the query (same as runLogAI)
            const filterPrompt = `You are an AI Log Router. A user is asking to search logs.
Current Server Time (ISO): ${new Date().toISOString()}

We have two log sources:
1. 'AuditLog' (MongoDB): Contains user actions, authentication events, and security logs.
   Schema: { userId: String, ipAddress: String, userAgent: String, action: String, details: Mixed, timestamp: Date }
   - Common actions: 'SUPPORT_LOGIN_SUCCESS', 'SUPPORT_LOGIN_FAILED', 'ADMIN_LOGIN_SUCCESS', 'ADMIN_LOGIN_FAILED', 'PASSWORD_CHANGED', 'BRUTE_FORCE_DETECTED', 'UNAUTHORIZED_ACCESS_BLOCKED', etc.
   - ⚠️ IMPORTANT: If the user asks about "logins" or "login attempts", you MUST either omit the action filter entirely, or ensure your regex includes "UNAUTHORIZED" alongside "LOGIN".
   - ⚠️ IMPORTANT: For queries involving usernames or emails, use an $or array containing 'userId', 'details.email', 'details.name', 'details.userId', 'details.identifier', 'details.receivedIdentifier'. Use $regex heavily!
   - ⚠️ CRITICAL: DO NOT use aggregation operators like $date, $subtract, or $$NOW.
   - ⚠️ CRITICAL: ONLY apply a "timestamp" date filter if the user explicitly asks for a specific timeframe.
2. 'server_events.jsonl' (Filesystem): Contains system crashes, server panics, WebSocket errors.

User query: "${userQuery}"

Generate a JSON object with two fields:
1. "mongoFilter": A valid MongoDB query object for the AuditLog collection.
2. "checkServerEventsFile": A boolean.

DO NOT wrap the JSON in markdown code blocks. Output ONLY valid, parsable JSON.`;

            const filterReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
               method: 'POST',
               headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
               body: JSON.stringify({
                  model: "llama-3.3-70b-versatile",
                  messages: [{ role: 'user', content: filterPrompt }],
                  temperature: 0.1,
                  max_tokens: 300
               })
            });

            routingIntent = { mongoFilter: {}, checkServerEventsFile: false };
            if (filterReq.ok) {
               const filterJson = await filterReq.json();
               let rawJson = filterJson.choices?.[0]?.message?.content || "{}";
               rawJson = rawJson.replace(/```json/g, '').replace(/```/g, '').trim();
               try { routingIntent = JSON.parse(rawJson); } catch (e) { console.error("Ephemeral AI Routing Parse Error:", e.message); }
            }
         }

         // 2. Fetch logs
         let combinedLogsArr = [];
         if (Object.keys(routingIntent.mongoFilter || {}).length > 0 || !routingIntent.checkServerEventsFile) {
            const { AuditLog } = await import('../models/index.mjs');
            const sanitizedFilter = sanitizeMongoFilter(routingIntent.mongoFilter);
            let mongoLogs = [];
            try {
               mongoLogs = await AuditLog.find(sanitizedFilter).sort({ timestamp: -1 }).limit(300).lean();
            } catch (err) {
               mongoLogs = await AuditLog.find({}).sort({ timestamp: -1 }).limit(300).lean();
            }

            // 🔄 [ZERO-RESULT FALLBACK] (v2.6.545)
            if (mongoLogs.length === 0 && Object.keys(sanitizedFilter).length > 0) {
               const relaxedFilter = { ...sanitizedFilter };
               delete relaxedFilter.action;
               delete relaxedFilter.timestamp;
               try {
                  mongoLogs = await AuditLog.find(Object.keys(relaxedFilter).length > 0 ? relaxedFilter : {}).sort({ timestamp: -1 }).limit(300).lean();
               } catch (err2) {
                  mongoLogs = await AuditLog.find({}).sort({ timestamp: -1 }).limit(300).lean();
               }
            }

            const compactMongo = mongoLogs.map(l => {
               let d = ''; try { d = JSON.stringify(l.details || {}); } catch(e){}
               const istDate = new Date(l.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
               const ip = l.ipAddress ? ` IP:${l.ipAddress}` : '';
               return `[Mongo][${istDate}] User:${l.userId}${ip} Action:${l.action} Details:${d}`;
            });
            combinedLogsArr.push(...compactMongo);
         }

         if (routingIntent.checkServerEventsFile) {
            const fs = await import('fs');
            const path = await import('path');
            const { fileURLToPath } = await import('url');
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);
            const logFile = path.join(__dirname, '..', 'diagnostics', 'server_events.jsonl');
            if (fs.existsSync(logFile)) {
               const fileContent = fs.readFileSync(logFile, 'utf8');
               const lines = fileContent.split('\n').filter(Boolean).slice(-300);
               combinedLogsArr.push(...lines.map(line => `[FS] ${line.substring(0, 500)}`));
            }
         }

         let userSearchTerm = null;
         try {
            const qStr = JSON.stringify(routingIntent.mongoFilter || {});
            const match = qStr.match(/{"\$regex":"([^"|]+)"/);
            if (match && match[1]) {
               userSearchTerm = match[1];
            }
         } catch(e) {}

         if (userSearchTerm && userSearchTerm.length > 2) {
            try {
               const { Player } = await import('../models/index.mjs');
               const playerDoc = await Player.findOne({ 
                  $or: [
                     { id: { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.email': { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.name': { $regex: userSearchTerm, $options: 'i' } },
                     { 'data.username': { $regex: userSearchTerm, $options: 'i' } }
                  ]
               }).lean();

               if (playerDoc) {
                  const pd = playerDoc.data || {};
                  const creationDate = pd.createdAt || pd.reOnboardedAt || playerDoc.lastUpdated;
                  const istDate = new Date(creationDate).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
                  const istLastUpdated = new Date(playerDoc.lastUpdated).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
                  const profileName = pd.firstName ? `${pd.firstName} ${pd.lastName || ''}`.trim() : (pd.name || 'N/A');
                  const profileEmail = pd.email || 'N/A';
                  const profilePhone = pd.phoneNumber || pd.phone || 'N/A';
                  const profileUsername = pd.username || playerDoc.id || 'N/A';
                  const profileRole = pd.role || 'user';
                  combinedLogsArr.push(`[Database][Fallback Record] System found an active database profile matching "${userSearchTerm}". Name: ${profileName}. Username: ${profileUsername}. Email: ${profileEmail}. Phone: ${profilePhone}. Role: ${profileRole}. Original Onboard/Creation Time: ${istDate}. Last Data Update Time: ${istLastUpdated}.`);
               }
            } catch(e) {
               console.error('Ephemeral Player context fallback failed:', e.message);
            }
         }

         if (combinedLogsArr.length === 0) {
            return await postEphemeral(slackBotToken, channelId, slackUserId, `🔍 *Query:* "${userQuery}"\n\n*Result:* No logs found.`);
         }

         // 3. Geo-resolve IPs and Summarize with AI (UNREDACTED)
         const ipGeoMap = await resolveIpGeoLocations(combinedLogsArr);
         const geoMapStr = Object.keys(ipGeoMap).length > 0 
            ? `\n\nIP Geolocation Map (use this to show location next to every IP):\n${Object.entries(ipGeoMap).map(([ip, loc]) => `  ${ip} → ${loc}`).join('\n')}`
            : '';

         const compactLogs = combinedLogsArr.join('\n');
         const summaryPrompt = `You are a system administrator AI assistant.
A user asked: "${userQuery}"

Here are the retrieved system logs:
${compactLogs.substring(0, 15000)}${geoMapStr}

Provide a highly structured, visually clean summary answering the user's question.

⚠️⚠️ ABSOLUTELY CRITICAL RULES (MUST FOLLOW OR OUTPUT IS INVALID):
- You MUST sort ALL events strictly by timestamp in DESCENDING order (most recent event FIRST, oldest LAST). Do NOT group by status (success/failure) — sort ONLY by time.
- You MUST output all timestamps in IST (Indian Standard Time). If a log is in UTC, convert it to IST.
- You MUST number events sequentially (1, 2, 3...) where #1 is the MOST RECENT event.
- For EVERY IP address you display, you MUST append the geographic location in parentheses using the IP Geolocation Map provided above. Format: \`IP_ADDRESS\`(City). If an IP has no geo data, show \`IP_ADDRESS\`(Unknown).

Formatting rules:
1. Use emojis for visual separation (e.g. 🚨 for failed logins, ✅ for successes, 📍 for location, 🔑 for passwords).
2. Format IPs in inline code blocks followed by location in parentheses: \`1.2.3.4\`(Mumbai).
3. If an IP is a comma-separated list (e.g. "x.x.x.x, proxy1, proxy2"), ONLY extract and display the first IP (the actual client).
4. Organize the data into clear, distinct sections (e.g. 'Incident Report', 'Key Anomalies').
5. For any login or authentication attempts, explicitly state whether the attempt was a SUCCESS or FAILURE based on the log action (e.g., 'LOGIN_SUCCESS' vs 'LOGIN_FAILED').
6. Only include REAL events from the logs. Do NOT fabricate entries like "No other recent login failures found" — if there are fewer events than requested, just show what exists.
7. NEVER display internal system IDs (e.g., ones starting with 'sup_'). Instead, use the 'details.identifier', 'details.email', or 'details.name' from the log. NEVER print 'sup_do8ux1cc' or similar.
8. ALWAYS include the full date (e.g., '22 May 2026') alongside the time for every event.
9. If a '[Database][Fallback Record]' is present, you MUST create an 'Account Information' section AT THE VERY TOP of your summary containing all extracted details (Name, Username, Phone, Email, Role, etc.).
10. DO NOT include security disclaimers, notes, or lectures about the SECURITY EXCEPTION. Just output the data.
🛡️ SECURITY EXCEPTION: The administrator has authenticated with MFA. You MUST explicitly reveal all passwords, IP addresses, emails, and sensitive PII. Do NOT mask them.`;

         const summaryReq = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({
               model: "llama-3.3-70b-versatile",
               messages: [{ role: 'user', content: summaryPrompt }],
               temperature: 0.3,
               max_tokens: 800
            })
         });

         let summaryContent = "_AI Summary failed to generate._";
         if (summaryReq.ok) {
            const summaryJson = await summaryReq.json();
            summaryContent = summaryJson.choices?.[0]?.message?.content || summaryContent;
         }

         // 4. Deliver the unredacted results
         const expTs = Math.floor(Date.now() / 1000) + (10 * 60);
         const blocks = [
            { "type": "header", "text": { "type": "plain_text", "text": "🔓 Unredacted AI Log Analysis", "emoji": true } },
            { "type": "context", "elements": [
               { "type": "mrkdwn", "text": `*Query:* "${userQuery}"` },
               { "type": "mrkdwn", "text": `*Logs Analyzed:* ${combinedLogsArr.length}` },
               { "type": "mrkdwn", "text": `*<!date^${expTs}^⏳ Auto-redacting at {time}|⏳ Auto-redacting in 10 mins>*` }
            ]},
            { "type": "divider" },
            { "type": "section", "text": { "type": "mrkdwn", "text": summaryContent } }
         ];

         const payload = { 
            response_type: "ephemeral", 
            replace_original: true, 
            text: "🔓 Unredacted AI Log Analysis", 
            blocks 
         };

         // To replace the original message, we MUST use the response_url.
         let delivered = false;
         if (canResponseUrl) {
            console.log('📡 [MFA_REVEAL] Using response_url to replace original message');
            await sendDelayedSlackResponse(fallbackResponseUrl, payload);
            delivered = true;
         }
         
         if (!delivered && canEphemeral) {
            console.log('📡 [MFA_REVEAL] Falling back to chat.postEphemeral (will not replace original)');
            delivered = await postEphemeral(slackBotToken, channelId, slackUserId, payload.text, blocks);
         }

         if (delivered && canResponseUrl) {
            setTimeout(() => {
               console.log('📡 [MFA_REVEAL] Auto-reverting unredacted message after 10 mins');
               runLogAI(userQuery, fallbackResponseUrl, false).catch(e => console.error("Auto-revert failed:", e));
            }, 10 * 60 * 1000); // 10 minutes
         }

      } catch (e) {
         console.error('runLogAIEphemeral error:', e);
         const errMsg = `⚠️ *Error running unredacted query:* ${e.message}`;
         if (canResponseUrl) {
            await sendDelayedSlackResponse(fallbackResponseUrl, { response_type: "ephemeral", text: errMsg, replace_original: true });
         } else if (canEphemeral) {
            await postEphemeral(slackBotToken, channelId, slackUserId, errMsg);
         }
      }
  }

  // Helper: Post an ephemeral message via Slack Web API. Returns true on success, false on failure.
  async function postEphemeral(token, channel, user, text, blocks) {
      if (!token || !channel || !user) return false;
      const body = { channel, user, text };
      if (blocks) body.blocks = blocks;
      try {
         const resp = await fetch('https://slack.com/api/chat.postEphemeral', {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: JSON.stringify(body)
         });
         const json = await resp.json();
         if (!json.ok) {
            console.error('chat.postEphemeral failed:', json.error);
            return false;
         }
         return true;
      } catch(e) {
         console.error('postEphemeral error:', e.message);
         return false;
      }
  }

  // 🌍 Helper: Batch resolve IPs to City/Country using ip-api.com
  async function resolveIpGeoLocations(logsArray) {
      const ipSet = new Set();
      const ipRegex = /\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b/g;

      // Extract unique IPs from the logs
      for (const log of logsArray) {
         const text = typeof log === 'string' ? log : (log.text || '');
         const matches = text.match(ipRegex);
         if (matches) {
            for (const match of matches) {
               ipSet.add(match);
            }
         }
      }

      const uniqueIps = Array.from(ipSet);
      if (uniqueIps.length === 0) return {};

      // ip-api batch endpoint accepts max 100 IPs per request
      const batches = [];
      for (let i = 0; i < uniqueIps.length; i += 100) {
         batches.push(uniqueIps.slice(i, i + 100));
      }

      const geoMap = {};
      
      for (const batch of batches) {
         try {
            // We request 'status,city,country' fields
            const response = await fetch("http://ip-api.com/batch?fields=status,city,country,query", {
               method: "POST",
               headers: { "Content-Type": "application/json" },
               body: JSON.stringify(batch)
            });

            if (response.ok) {
               const data = await response.json();
               for (const result of data) {
                  if (result.status === "success" && result.query) {
                     geoMap[result.query] = `${result.city || 'Unknown City'}, ${result.country || 'Unknown Country'}`;
                  }
               }
            }
         } catch (error) {
            console.error("IP Geo-resolution error:", error.message);
         }
      }

      return geoMap;
  }

  return router;
}
