import { StyleSheet, Dimensions } from 'react-native';
import { colors, shadows } from '../../theme/designSystem';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  premiumHeader: {
    backgroundColor: '#0F172A',
    paddingBottom: 24,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 20 : 40,
    marginBottom: 20,
  },
  welcomeLabel: {
    fontSize: 10,
    fontWeight: '900',
    color: 'rgba(255, 255, 255, 0.6)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  academyNameText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
    marginTop: 2,
  },
  premiumAddBtn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  statsDashboard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    borderRadius: 24,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  dashStatCard: {
    flex: 1,
    alignItems: 'center',
  },
  dashStatVal: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  dashStatLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  dashStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#E2E8F0',
  },
  segmentedTabContainer: {
    paddingHorizontal: 20,
    marginTop: -20,
    zIndex: 20,
  },
  segmentedTabBar: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  segTab: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  segTabActive: {
    backgroundColor: '#EEF2FF',
  },
  segTabText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#94A3B8',
  },
  segTabTextActive: {
    color: '#6366F1',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  downloadFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4
  },
  downloadFilterText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6366F1'
  },
  filterBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.navy[100],
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterBtnActive: {
    backgroundColor: colors.navy[900],
    borderColor: colors.navy[900],
  },
  filterBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.navy[500],
  },
  filterBtnTextActive: {
    color: '#FFFFFF',
  },
  premiumCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.md,
    borderWidth: 1,
    borderColor: colors.navy[100],
  },
  premiumCardBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  tCardMainInfo: {
    flex: 1,
    gap: 4,
  },
  sportBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  sportBadgeTextSmall: {
    fontSize: 9,
    fontWeight: '900',
    color: '#6366F1',
    textTransform: 'uppercase',
  },
  premiumTTitle: {
    ...typography.h2,
    color: colors.navy[900],
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationTextSmall: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.navy[400],
  },
  premiumEditBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.navy[50],
    justifyContent: 'center',
    alignItems: 'center',
  },
  premiumTInfoGrid: {
    flexDirection: 'row',
    backgroundColor: colors.navy[50],
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
  },
  infoGridItem: {
    flex: 1,
    alignItems: 'center',
  },
  infoGridLabel: {
    fontSize: 8,
    fontWeight: '800',
    color: colors.navy[400],
    textTransform: 'uppercase',
  },
  infoGridValue: {
    fontSize: 11,
    fontWeight: '900',
    color: colors.navy[700],
    marginTop: 2,
  },
  premiumCoachSection: {
    backgroundColor: '#EEF2FF',
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  premiumCoachHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  premiumCoachAvatar: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  premiumCoachLabel: {
    fontSize: 8,
    fontWeight: '800',
    color: '#6366F1',
    textTransform: 'uppercase',
  },
  premiumCoachName: {
    fontSize: 12,
    fontWeight: '900',
    color: colors.primary.dark,
  },
  premiumOtpTrigger: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pViewOtpBtn: {
    paddingHorizontal: 4,
  },
  pViewOtpText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#6366F1',
  },
  premiumOtpBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  pOtpVal: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 1,
  },
  pOtpLine: {
    width: 1,
    height: 12,
    backgroundColor: '#E2E8F0',
  },
  premiumCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  premiumPrimaryBtn: {
    flexDirection: 'row',
    backgroundColor: colors.navy[900],
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    gap: 6,
  },
  premiumPrimaryBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
    marginRight: 6,
  },
  footerDeleteButton: {
    fontSize: 14,
    fontWeight: '700',
    color: '#EF4444',
    textDecorationLine: 'underline'
  },
  premiumStatusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusPillActive: { backgroundColor: '#FEF2F2', borderColor: '#FEE2E2' },
  statusPillPast: { backgroundColor: '#F1F5F9', borderColor: '#E2E8F0' },
  interestBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: colors.warning,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    zIndex: 10
  },
  interestBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900'
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  premiumStatusText: {
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  tCardPast: {
    opacity: 0.8,
    backgroundColor: '#F8FAFC',
  },
  emptyView: {
    paddingVertical: 80,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#CBD5E1',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  modalScroll: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  formTitle: {
    ...typography.h2,
    color: colors.navy[900],
    textTransform: 'uppercase',
  },
  formCloseBtn: {
    padding: 4,
  },
  formContent: {
    padding: 24,
    gap: 20,
  },
  inputGroup: {
    gap: 8,
  },
  gridRow: {
    flexDirection: 'row',
    gap: 12,
  },
  fieldLabel: {
    ...typography.micro,
    color: colors.navy[400],
    paddingLeft: 4,
  },
  formInput: {
    backgroundColor: colors.navy[50],
    borderRadius: borderRadius.lg,
    padding: 16,
    ...typography.body,
    color: colors.navy[900],
    borderWidth: 1,
    borderColor: colors.navy[100],
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  pickerBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  pickerBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
  coachAssignmentSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 16,
  },
  coachSectionTitle: {
    fontSize: 10,
    fontWeight: '900',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  assignmentBtnRow: {
    gap: 10,
  },
  assignmentBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  assignmentBtnActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#DBEAFE',
  },
  assignmentBtnText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#64748B',
  },
  assignmentBtnTextActive: {
    color: '#1E40AF',
  },
  academyCoachForm: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 24,
    gap: 16,
  },
  otherCoachFields: {
    gap: 12,
  },
  platformCoachInfo: {
    flexDirection: 'row',
    backgroundColor: '#EFF6FF',
    padding: 16,
    borderRadius: 20,
    gap: 12,
    alignItems: 'center',
  },
  platformInfoText: {
    flex: 1,
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1E40AF',
    lineHeight: 16,
  },
  formFooter: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    paddingBottom: 40,
  },
  saveBtn: {
    flex: 1,
    backgroundColor: colors.navy[900],
    paddingVertical: 18,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    ...shadows.lg,
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  cancelBtn: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    alignItems: 'center',
    minWidth: 100,
  },
  cancelBtnText: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: '60%',
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  pickerTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    textTransform: 'uppercase',
  },
  pickerList: {
    padding: 16,
  },
  pickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 16,
    marginBottom: 4,
  },
  pickerItemText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#334155',
  },
  pickerItemTextActive: {
    color: '#3B82F6',
  },
  flex: { flex: 1 },
  autofillBtn: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginLeft: 10,
  },
  autofillBtnText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#6366F1',
    textTransform: 'uppercase',
  },
  broadcastContainer: {
    paddingTop: 10,
  },
  broadcastHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  broadcastIconBg: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  broadcastTitle: {
    ...typography.h2,
    color: colors.navy[900],
  },
  broadcastSubtitle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94A3B8',
    marginTop: 2,
    lineHeight: 16,
  },
  broadcastCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
});

export default AcademyScreen;
