import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, shadows, typography, borderRadius, spacing } from '../../theme/designSystem';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F1F5F9' },
  mainLayout: { flex: 1, flexDirection: 'row' },

  // ─── Contact Panel ───────────────
  contactPanel: {
    width: 340,
    backgroundColor: '#0F172A', // Dark sidebar theme
    borderRightWidth: 1,
    borderRightColor: '#1E293B',
    ...Platform.select({ web: { maxWidth: 340, minWidth: 280 } }),
  },
  contactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  contactHeaderTitle: { fontSize: 22, fontWeight: '900', color: '#FFFFFF', letterSpacing: -0.3 },
  contactCloseBtn: { padding: 4 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  searchInput: { flex: 1, marginLeft: 10, fontSize: 14, color: '#FFFFFF', ...Platform.select({ web: { outlineStyle: 'none' } }) },
  contactList: { flex: 1 },
  emptyContacts: { alignItems: 'center', marginTop: 60 },
  emptyText: { color: '#94A3B8', marginTop: 12, fontSize: 14 },

  // ─── Contact Item ───────────────
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  contactItemActive: { backgroundColor: '#1E293B' },
  contactItemUnread: {
    backgroundColor: 'rgba(99, 102, 241, 0.2)'
  },
  avatarContainer: {
    marginRight: 14,
    position: 'relative'
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarOnlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#0F172A'
  },
  avatarActive: { backgroundColor: '#6366F1' },
  avatarText: { fontSize: 15, fontWeight: '800', color: '#94A3B8' },
  contactInfo: { flex: 1 },
  contactNameRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  contactName: { fontSize: 14, fontWeight: '700', color: '#FFFFFF', flex: 1, marginRight: 8 },
  contactNameActive: { color: '#6366F1' },
  contactTime: { fontSize: 11, color: '#64748B', fontWeight: '500' },
  contactPreviewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  contactPreview: { fontSize: 12, color: '#94A3B8', flex: 1, marginRight: 8 },
  unreadBadge: { backgroundColor: '#6366F1', borderRadius: 10, minWidth: 20, height: 20, paddingHorizontal: 6, justifyContent: 'center', alignItems: 'center' },
  unreadText: { color: '#FFF', fontSize: 10, fontWeight: '800' },

  // ─── Chat Panel ───────────────
  chatPanel: { flex: 1, backgroundColor: '#FAFBFC' },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    zIndex: 1000,
  },
  chatHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  chatHeaderAvatarText: { color: '#FFF', fontSize: 14, fontWeight: '800' },
  chatHeaderName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    marginRight: 6
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500'
  },
  chatHeaderRole: { fontSize: 12, color: '#64748B', textTransform: 'capitalize' },
  contactCard: {
    position: 'absolute',
    top: 50,
    left: 0,
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 12,
    minWidth: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    zIndex: 100,
  },
  contactCardName: { fontSize: 14, fontWeight: '800', color: '#0F172A', marginBottom: 2 },
  contactCardDesig: { fontSize: 12, color: '#6366F1', fontWeight: '600', marginBottom: 8 },
  contactCardRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  contactCardText: { fontSize: 12, color: '#475569', marginLeft: 8 },

  // ─── Empty Chat ───────────────
  emptyChatContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  emptyChatIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  emptyChatTitle: { fontSize: 18, fontWeight: '800', color: '#334155', marginBottom: 8 },
  emptyChatSub: { fontSize: 14, color: '#94A3B8', textAlign: 'center' },

  // ─── Messages ───────────────
  messageArea: { flex: 1, backgroundColor: '#FAFBFC' },
  messageAreaContent: { padding: 20, paddingBottom: 10 },
  noMsgContainer: { alignItems: 'center', marginTop: 80 },
  noMsgText: { fontSize: 16, fontWeight: '700', color: '#94A3B8', marginTop: 12 },
  noMsgSub: { fontSize: 13, color: '#CBD5E1', marginTop: 4 },

  dateDivider: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
  dateLine: { flex: 1, height: 1, backgroundColor: '#E2E8F0' },
  dateText: { color: '#94A3B8', fontSize: 11, fontWeight: '700', marginHorizontal: 12, textTransform: 'uppercase' },

  msgRow: { flexDirection: 'row', marginBottom: 12, maxWidth: '75%' },
  msgRowMe: { alignSelf: 'flex-end', flexDirection: 'row-reverse' },
  msgRowOther: { alignSelf: 'flex-start' },
  msgAvatarSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    marginTop: 2,
  },
  msgAvatarSmallText: { fontSize: 10, fontWeight: '800', color: '#64748B' },
  msgBubble: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, maxWidth: '100%' },
  msgBubbleMe: { backgroundColor: '#6366F1', borderBottomRightRadius: 6 },
  msgBubbleOther: { backgroundColor: '#FFF', borderBottomLeftRadius: 6, borderWidth: 1, borderColor: '#E2E8F0' },
  msgContent: { fontSize: 14, color: '#1E293B', lineHeight: 20 },
  msgTimestamp: { fontSize: 10, color: '#94A3B8', marginTop: 4, alignSelf: 'flex-end' },

  // ─── Input Area ───────────────
  inputArea: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    fontSize: 14,
    color: '#0F172A',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    maxHeight: 100,
    marginRight: 10,
    ...Platform.select({ web: { outlineStyle: 'none' } }),
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendBtnDisabled: { backgroundColor: '#CBD5E1' },
  
  // ─── Attachments Styles ───────────
  attachBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
  pendingAttachmentsBar: {
    backgroundColor: '#F1F5F9',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    padding: 10,
  },
  pendingAttachmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  pendingAttachmentText: { fontSize: 12, color: '#334155', marginHorizontal: 6, maxWidth: 120 },
  attachmentContainer: { marginTop: 8, gap: 6 },
  imageAttachmentContainer: { width: '100%', marginBottom: 4 },
  imagePlaceholder: { width: '100%', backgroundColor: '#F1F5F9', borderRadius: 8, overflow: 'hidden' },
  fileAttachmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(99, 102, 241, 0.08)',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
  },
  fileName: { fontSize: 13, fontWeight: '700', color: '#1E293B' },
  fileSize: { fontSize: 11, color: '#64748B', marginTop: 2 },
  expiredAttachment: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    opacity: 0.8,
  },
  expiredText: { fontSize: 12, color: '#94A3B8', marginLeft: 8, fontWeight: '500' },

  // ─── Interaction Styles (v2.6.405) ───────────
  reactionRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6, gap: 4 },
  reactionChip: { backgroundColor: '#F1F5F9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center' },
  reactionCount: { fontSize: 10, color: '#64748B', marginLeft: 4, fontWeight: '700' },
  msgToolbar: { position: 'absolute', top: -40, flexDirection: 'row', backgroundColor: '#FFF', padding: 4, borderRadius: 20, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, zIndex: 100 },
  msgToolbarMe: { right: 0 },
  msgToolbarOther: { left: 0 },
  emojiStrip: { flexDirection: 'row', borderRightWidth: 1, borderRightColor: '#F1F5F9', paddingRight: 4 },
  emojiBtn: { paddingHorizontal: 8, paddingVertical: 4 },
  emojiBtnText: { fontSize: 16 },
  moreBtn: { paddingHorizontal: 10, justifyContent: 'center' },
  actionsDropdown: { position: 'absolute', top: 44, right: 0, backgroundColor: '#FFF', borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', width: 160, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12, zIndex: 1000, overflow: 'hidden' },
  actionsDropdownMe: { right: 0 },
  actionsDropdownOther: { left: 0 },
  actionItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  actionItemText: { fontSize: 13, marginLeft: 10, color: '#475569', fontWeight: '500' },
  replyQuote: { padding: 8, borderRadius: 8, marginBottom: 8, borderLeftWidth: 3, borderLeftColor: '#6366F1', backgroundColor: 'rgba(0,0,0,0.03)' },
  replyQuoteMe: { backgroundColor: 'rgba(255,255,255,0.15)', borderLeftColor: '#FFF' },
  replyQuoteOther: { backgroundColor: 'rgba(0,0,0,0.03)' },
  replyQuoteText: { fontSize: 12, fontStyle: 'italic', color: '#64748B' },
  replyPreviewBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', padding: 12, borderTopWidth: 1, borderTopColor: '#E2E8F0' },
  replyPreviewIndicator: { width: 4, height: '100%', backgroundColor: '#6366F1', borderRadius: 2 },
  replyPreviewContent: { flex: 1, marginLeft: 12 },
  replyPreviewName: { fontSize: 12, fontWeight: '700', color: '#6366F1' },
  replyPreviewText: { fontSize: 12, color: '#64748B', marginTop: 2 },
  replyPreviewClose: { padding: 4 },

  // 🔗 [SCROLL-TO-REPLY] (v2.6.424): Highlight overlay for blink effect
  highlightOverlay: {
    position: 'absolute',
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(99, 102, 241, 0.5)',
  },
  
  // 🖼️ Modal Styles (v2.6.466)
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.9)' },
  modalContent: { flex: 1 },
  modalClose: { position: 'absolute', top: 20, right: 20, zIndex: 10, padding: 10 },
  fullImage: { flex: 1, width: '100%' },
  modalFooter: { padding: 20, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center' },
  modalFilename: { color: '#FFF', fontSize: 14, fontWeight: '700', marginBottom: 16 },
  shareBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#6366F1', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12 },
  shareText: { color: '#FFF', marginLeft: 10, fontWeight: '800' },

  // 💡 Reaction Tooltip Styles (v2.6.468)
  reactionTooltip: {
    position: 'absolute',
    bottom: 30,
    backgroundColor: '#1E293B',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    minWidth: 100,
    zIndex: 100,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5
  },
  reactionTooltipMe: { right: 0 },
  reactionTooltipOther: { left: 0 },
  reactionTooltipText: { color: '#FFF', fontSize: 10, fontWeight: '600' },
  
  msgBubbleActive: {
    backgroundColor: '#EEF2FF',
    borderColor: '#6366F1',
    borderWidth: 1,
    transform: [{ scale: 0.98 }]
  },
  replyThumbnail: {
    width: 32,
    height: 32,
    borderRadius: 6,
    marginRight: 8,
    backgroundColor: '#E2E8F0'
  },
});

export default OrgChatScreen;
