import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, shadows } from '../../theme/designSystem';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  content: { padding: 20 },
  academyHeader: { paddingHorizontal: 24, paddingTop: 40, paddingBottom: 16, backgroundColor: '#FFFFFF' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, marginTop: 40 },
  welcomeText: { ...typography.h1, color: colors.navy[900] },
  subText: { ...typography.caption, color: colors.navy[500], marginTop: 2 },
  refreshBtn: { width: 46, height: 46, borderRadius: 14, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center', ...shadows?.sm },
  statsGrid: { 
    flexDirection: 'row', 
    justifyContent: 'flex-start', 
    marginBottom: 24, 
    flexWrap: 'wrap', 
    gap: 10,
    width: '100%',
  },
  statBox: { 
    backgroundColor: '#fff', 
    width: '47%', 
    padding: 14, 
    borderRadius: borderRadius.lg, 
    ...shadows.sm 
  },
  iconCircle: { width: 36, height: 36, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  statValue: { ...typography.h2, color: colors.navy[900] },
  statTitle: { ...typography.micro, color: colors.navy[400], marginBottom: 6 },
  trendRow: { flexDirection: 'row', alignItems: 'center' },
  trendText: { fontSize: 9, color: colors.success, fontWeight: '700', marginLeft: 2 },
  chartCard: { backgroundColor: '#fff', borderRadius: borderRadius.xl, padding: 20, marginBottom: 20, ...shadows.sm },
  chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  chartHeaderExpanded: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  chartTitle: { fontSize: 17, fontWeight: '700', color: '#1E293B' },
  chartSubtitle: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  barChartContainer: { marginTop: 10 },
  barRow: { marginBottom: 18 },
  barLabelContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6, paddingHorizontal: 2 },
  barLabel: { fontSize: 13, fontWeight: '700', color: '#334155', flex: 1 },
  barValue: { fontSize: 12, fontWeight: '800', color: '#1E293B', marginRight: 8 },
  newLabel: { fontSize: 10, color: '#10B981', fontWeight: '700', marginTop: 1 },
  barTrack: { height: 8, backgroundColor: colors.navy[100], borderRadius: 4, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 4 },
  drillInfoBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EEF2FF', padding: 10, borderRadius: 10, marginBottom: 12, gap: 8 },
  drillInfoText: { fontSize: 11, color: '#4F46E5', fontWeight: '500', flex: 1 },
  areaDetail: { marginTop: 4 },
  areaHero: { backgroundColor: '#F8FAFC', padding: 16, borderRadius: 16, marginBottom: 20 },
  areaHeroTitle: { fontSize: 18, fontWeight: '800', color: '#1E293B', marginBottom: 4 },
  areaHeroCount: { fontSize: 13, fontWeight: '700', color: '#6366F1' },
  subChartTitle: { fontSize: 14, fontWeight: '700', color: '#475569', marginBottom: 16, marginLeft: 2 },
  detailBarRow: { marginBottom: 14 },
  playerList: { marginTop: 8 },
  playerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, backgroundColor: '#fff', padding: 10, borderRadius: 12, borderContent: '#F1F5F9', borderWidth: 1 },
  playerName: { flex: 1, fontSize: 13, fontWeight: '600', color: '#334155', marginLeft: 10 },
  playerTag: { backgroundColor: '#EEF2FF', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  playerTagText: { fontSize: 9, fontWeight: '700', color: '#6366F1' },
  growthContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 160, marginTop: 4, paddingHorizontal: 4 },
  growthColumn: { alignItems: 'center', flex: 1 },
  platformInsightsSection: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 20,
    marginTop: 8
  },
  rowAlign: { flexDirection: 'row', alignItems: 'center' },
  statusMiniBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginLeft: 8 },
  statusMiniText: { fontSize: 9, fontWeight: '800', textTransform: 'uppercase' },
  growthBar: { width: 14, backgroundColor: '#6366F1', borderRadius: 6, opacity: 0.8 },
  growthLabel: { fontSize: 10, color: '#94A3B8', marginTop: 8, fontWeight: '700' },
  growthBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EEF2FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  growthBadgeText: { ...typography.caption, color: colors.primary.base, marginLeft: 4 },
  pctContainer: { height: 20, justifyContent: 'flex-end', marginBottom: 4 },
  pctText: { fontSize: 9, fontWeight: '800', color: '#10B981' },
  flexItem: { flex: 1 },
  backBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EEF2FF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  backBtnText: { fontSize: 12, fontWeight: '700', color: '#6366F1', marginLeft: 4 },
  academyList: { marginTop: 4 },
  academyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F8FAFC' },
  academyRank: { width: 24, height: 24, borderRadius: 6, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  rankText: { fontSize: 11, fontWeight: '800' },
  academyName: { fontSize: 14, fontWeight: '700', color: '#334155', flex: 1 },
  academyTournaments: { fontSize: 12, fontWeight: '700', color: '#1E293B' },
  academyDetail: { paddingVertical: 8 },
  detailName: { fontSize: 16, fontWeight: '700', color: '#334155', marginBottom: 12 },
  detailStatsRow: { flexDirection: 'row', gap: 20 },
  detailStat: { alignItems: 'center' },
  detailStatVal: { fontSize: 16, fontWeight: '800', color: '#6366F1' },
  detailStatLabel: { fontSize: 9, color: '#94A3B8', fontWeight: '700', textTransform: 'uppercase' },
  geoContainer: { marginTop: 4 },
  geoRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#F8FAFC' },
  dot: { width: 10, height: 10, borderRadius: 5, marginRight: 12 },
  geoName: { flex: 1, fontSize: 14, fontWeight: '600', color: '#334155' },
  geoCount: { fontSize: 13, fontWeight: '700', color: '#1E293B' },
  deviceDetailContainer: { marginTop: 10 },
  deviceSplitRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  deviceCol: { flex: 1, backgroundColor: '#F8FAFC', padding: 12, borderRadius: 12 },
  deviceTitle: { fontSize: 10, fontWeight: '700', color: '#94A3B8', textTransform: 'uppercase' },
  deviceCount: { fontSize: 18, fontWeight: '800', color: '#1E293B' },
  deviceUserRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F8FAFC', padding: 12, borderRadius: 12, marginBottom: 8 },
  deviceUserName: { fontSize: 13, fontWeight: '700', color: '#334155' },
  deviceUserId: { fontSize: 10, color: '#94A3B8', marginTop: 2 },
  appVersionBadge: { backgroundColor: '#EEF2FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  appVersionText: { fontSize: 10, fontWeight: '800', color: '#6366F1' },
  platformIconBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', padding: 10, borderRadius: 12, flex: 1, marginRight: 10, justifyContent: 'center' },
  platformIconText: { fontSize: 12, fontWeight: '700', color: '#334155', marginLeft: 8 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  tapToSearch: { fontSize: 9, fontWeight: '700', color: '#6366F1', marginTop: 4, fontStyle: 'italic' },
  modalFullContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 24, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  modalTitle: { fontSize: 22, fontWeight: '800', color: '#1E293B' },
  modalSubtitle: { fontSize: 11, color: '#94A3B8', fontWeight: '700', textTransform: 'uppercase', marginTop: 2 },
  searchBarWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', margin: 24, marginTop: 12, marginBottom: 12, paddingHorizontal: 16, borderRadius: 14, height: 48, borderWidth: 1, borderColor: '#F1F5F9' },
  modalSearchInput: { flex: 1, height: '100%', fontSize: 14, color: '#1E293B', fontWeight: '600' },
  searchIcon: { marginRight: 10 },
  modalContent: { flex: 1 },
  modalScrollContent: { padding: 24, paddingTop: 0 },
  emptyState: { alignItems: 'center', justifyContent: 'center', marginTop: 100 },
  emptyStateText: { fontSize: 13, color: '#94A3B8', fontStyle: 'italic' },
});

export default InsightsScreen;
